import React from 'react';
import {interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {BaseSceneProps} from '../VideoSpec.schema';
import {getSafeArea} from '../lib/safeArea';
import {fitOneLine, fitWrapped} from '../theme/layout';
import {useStyle} from '../theme/StyleContext';
import {asNumber, asRows, asText, clamp01, SafeFlex, SafeRow} from './expansion_shared';
import {CameraPreset, FallbackShape, MaterialMode, Universal3DViewport} from './three/Universal3D';

type Props = BaseSceneProps & Record<string, unknown>;
const text=(v:unknown,f='')=>asText(v,f);
const camera=(v:unknown):CameraPreset=>['orbit','arc','dolly','figureEight'].includes(text(v))?text(v) as CameraPreset:'orbit';
const material=(v:unknown):MaterialMode=>['original','clay','glass','wireframe'].includes(text(v))?text(v) as MaterialMode:'original';
const shape=(v:unknown,f:FallbackShape):FallbackShape=>['orb','cube','ring','chip','nodes'].includes(text(v))?text(v) as FallbackShape:f;

const ThreeOverlay: React.FC<{props:BaseSceneProps; title:string; meta:string; assetUrl?:string; fallback:FallbackShape; children?:React.ReactNode}> = ({props,title,meta,assetUrl,fallback,children}) => { const p=props as Props; const {width,height}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const safe=getSafeArea(width,height,props.safeArea??'platform'); const titleSize=fitWrapped({text:title,maxWidth:safe.width*.82,maxLines:3,fontFamily:fonts.display,fontWeight:900,maxFontSize:Math.round(height*.042),minFontSize:Math.round(height*.024),lineHeight:1.02});
 return <div style={{position:'absolute',inset:0,overflow:'hidden',background:theme.bg}}><Universal3DViewport assetUrl={assetUrl||text(p.assetUrl,text(p.modelUrl))} accent={accent} background={theme.bg} cameraPreset={camera(p.cameraPreset)} materialMode={material(p.materialMode)} fallbackShape={shape(p.fallbackShape,fallback)}/><div style={{position:'absolute',inset:0,background:`linear-gradient(180deg,${theme.bg}99 0%,transparent 36%,${theme.bg}BB 100%)`,pointerEvents:'none'}}/><div style={{position:'absolute',top:safe.top,left:safe.left,width:safe.width,height:safe.height,boxSizing:'border-box',display:'flex',flexDirection:'column',justifyContent:'space-between',minWidth:0}}><div><div style={{fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.017),letterSpacing:1.8}}>{meta}</div><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:titleSize.fontSize,lineHeight:1.02,marginTop:7,maxWidth:'82%'}}>{title}</div></div>{children}</div></div>; };

/** 33 — Slow orbit around licensed external asset or procedural fallback. */
export const AssetOrbit3D: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); return <ThreeOverlay props={props} title={text(p.title,text(p.label,'ОБЛЁТ 3D-МОДЕЛИ'))} meta={text(p.assetLicense,'LICENSED 3D ASSET')} fallback="orb"><div style={{alignSelf:'flex-start',maxWidth:'72%',padding:'10px 14px',borderRadius:14,background:`${theme.bg}CC`,border:`1px solid ${accent}77`,fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.018),lineHeight:1.2}}>{text(p.assetAttribution,text(p.caption,'Передайте свой GLB/glTF или ссылку на разрешённый к использованию ассет.'))}</div></ThreeOverlay>; };

/** 34 — Labeled exploded layers with procedural fallback. */
export const ExplodedProductView: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,durationInFrames}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const parts=asRows(p.parts).slice(0,4); const rows=parts.length?parts:[{label:'Интерфейс'},{label:'Логика'},{label:'Данные'}]; const q=interpolate(frame,[0,durationInFrames*.5,durationInFrames-1],[0,1,0.35],{extrapolateRight:'clamp'});
 return <ThreeOverlay props={props} title={text(p.title,'РАЗБОР ОБЪЕКТА НА СЛОИ')} meta="EXPLODED VIEW" fallback="chip"><div style={{display:'flex',flexDirection:'column',gap:9,alignSelf:'flex-start',marginBottom:Math.round(height*.02)}}>{rows.map((part,i)=><div key={i} style={{transform:`translateX(${Math.round(q*(i%2?1:-1)*width*.04)}px)`,padding:'7px 10px',borderRadius:12,background:`${theme.bg}CC`,border:`1px solid ${i===0?accent:`${theme.muted}66`}`,fontFamily:fonts.display,color:i===0?accent:theme.text,fontSize:Math.round(height*.016),fontWeight:850}}>{String(i+1).padStart(2,'0')} · {text(part.label,`Слой ${i+1}`)}</div>)}</div></ThreeOverlay>; };

/** 35 — Camera-driven pipeline corridor. */
export const WorkflowFlyThrough3D: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const nodes=asRows(p.workflowNodes).slice(0,7); const rows=nodes.length?nodes:[{label:'Research'},{label:'Benchmark'},{label:'Review'},{label:'Render'}]; const active=Math.min(rows.length-1,Math.floor(frame/Math.max(1,fps*1.3)));
 return <ThreeOverlay props={props} title={text(p.title,'ПРОЛЁТ ПО WORKFLOW')} meta="3D PIPELINE" fallback="nodes"><div style={{display:'flex',gap:7,flexWrap:'wrap',alignSelf:'flex-start',marginBottom:Math.round(height*.02)}}>{rows.map((node,i)=><div key={i} style={{padding:'6px 9px',borderRadius:999,background:i===active?accent:`${theme.bg}CC`,color:i===active?theme.bg:theme.text,border:`1px solid ${i===active?accent:theme.muted}`,fontFamily:fonts.display,fontSize:Math.round(height*.014),fontWeight:900}}>{text(node.label,`Этап ${i+1}`)}</div>)}</div></ThreeOverlay>; };

/** 36 — Numeric X/Y/Z cube overlay. */
export const DataCube: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height,width}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const labels=Array.isArray(p.labels)?p.labels.filter((x):x is string=>typeof x==='string'):['Цена','Качество','Скорость']; const values=[asNumber(p.x),asNumber(p.y),asNumber(p.z)];
 return <ThreeOverlay props={props} title={text(p.title,'КУБ ДАННЫХ')} meta="3D DATA CUBE" fallback="cube"><div style={{alignSelf:'stretch',display:'flex',gap:Math.round(width*.018),marginBottom:Math.round(height*.015)}}>{labels.slice(0,3).map((label,i)=><SafeFlex key={label} style={{padding:'9px 10px',background:`${theme.bg}CC`,borderRadius:12,border:`1px solid ${i===asNumber(p.highlight,0)?accent:`${theme.muted}55`}`}}><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.014)}}>{label}</div><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.027),marginTop:2}}>{values[i]}</div></SafeFlex>)}</div></ThreeOverlay>; };

/** 37 — Brand SVG/logo material study. */
export const LogoSculpture3D: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); return <ThreeOverlay props={props} title={text(p.title,'ОБЪЁМНЫЙ ЗНАК')} meta="LOGO SCULPTURE" fallback="ring"><div style={{alignSelf:'flex-start',padding:'8px 11px',borderRadius:999,background:`${theme.bg}D9`,border:`1px solid ${accent}66`,fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.016)}}>{text(p.tagline,'ВАШ БРЕНД · ВАШ СТИЛЬ')}</div></ThreeOverlay>; };

/** 38 — Moving fleet of devices around a 3D core. */
export const DeviceConveyor3D: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const devices=Array.isArray(p.devices)?p.devices.filter((x):x is string=>typeof x==='string').slice(0,4):['PHONE','DESKTOP','TABLET']; const active=Math.min(devices.length-1,Math.floor(frame/Math.max(1,fps*1.4)));
 return <ThreeOverlay props={props} title={text(p.title,'УСТРОЙСТВА В ОДНОМ ПОТОКЕ')} meta="DEVICE CONVEYOR" fallback="chip"><SafeRow gap={Math.round(width*.02)} style={{marginBottom:Math.round(height*.015)}}>{devices.map((device,i)=><SafeFlex key={device} style={{padding:'8px 4px',textAlign:'center',borderRadius:10,background:i===active?accent:`${theme.bg}CC`,color:i===active?theme.bg:theme.text,border:`1px solid ${i===active?accent:theme.muted}`,fontFamily:fonts.display,fontSize:Math.round(height*.013),fontWeight:900}}>{device}</SafeFlex>)}</SafeRow></ThreeOverlay>; };

/** 39 — Particle field summary. */
export const ParticleDataField: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height,width}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const groups=asRows(p.groups).slice(0,4); const rows=groups.length?groups:[{label:'Сигналы',value:72},{label:'Шум',value:18},{label:'Фокус',value:10}];
 return <ThreeOverlay props={props} title={text(p.title,'ПОЛЕ ЧАСТИЦ')} meta="PARTICLE DATA FIELD" fallback="nodes"><div style={{alignSelf:'stretch',marginBottom:Math.round(height*.015),display:'flex',flexDirection:'column',gap:6}}>{rows.map((row,i)=><SafeRow key={i} gap={9} style={{alignItems:'center'}}><div style={{width:8,height:8,borderRadius:'50%',background:i===0?accent:theme.cyan}}/><SafeFlex style={{fontFamily:fonts.body,color:theme.text,fontSize:Math.round(height*.016)}}>{text(row.label,`Группа ${i+1}`)}</SafeFlex><div style={{fontFamily:fonts.display,color:i===0?accent:theme.text,fontWeight:900,fontSize:Math.round(height*.016)}}>{asNumber(row.value)}</div></SafeRow>)}</div></ThreeOverlay>; };

/** 40 — Isometric workflow city labels. */
export const IsometricWorkflowCity: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const zones=asRows(p.zones).slice(0,6); const rows=zones.length?zones:[{label:'Inbox'},{label:'Model'},{label:'Review'},{label:'Output'}]; const active=Math.min(rows.length-1,Math.floor(frame/Math.max(1,fps*1.2)));
 return <ThreeOverlay props={props} title={text(p.title,'ГОРОД ВАШЕГО WORKFLOW')} meta="ISOMETRIC WORKFLOW" fallback="cube"><div style={{alignSelf:'flex-start',display:'flex',flexWrap:'wrap',gap:7,marginBottom:Math.round(height*.018)}}>{rows.map((zone,i)=><div key={i} style={{padding:'6px 9px',borderRadius:10,background:i===active?accent:`${theme.bg}CC`,color:i===active?theme.bg:theme.text,fontFamily:fonts.display,fontSize:Math.round(height*.014),fontWeight:900}}>{text(zone.label,`Зона ${i+1}`)}</div>)}</div></ThreeOverlay>; };

/** 41 — Globe-like signal map with only supplied data. */
export const GlobeSignalMap: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const locations=asRows(p.locations).slice(0,5); const rows=locations.length?locations:[{label:'EU'},{label:'US'},{label:'APAC'}];
 return <ThreeOverlay props={props} title={text(p.title,'КАРТА СИГНАЛОВ')} meta={text(p.source,'SUPPLIED LOCATIONS')} fallback="orb"><div style={{alignSelf:'flex-start',padding:'9px 11px',borderRadius:12,background:`${theme.bg}CC`,fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.016)}}>{rows.map((location,i)=><span key={i} style={{color:i===0?accent:theme.muted,fontWeight:i===0?850:650}}>{i?' · ':''}{text(location.label,`Точка ${i+1}`)}</span>)}</div></ThreeOverlay>; };

/** 42 — Depth corridor of fact-backed milestones. */
export const MilestoneCorridor3D: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const milestones=asRows(p.milestones).slice(0,6); const rows=milestones.length?milestones:[{date:'Март',label:'Первый факт'},{date:'Июль',label:'Изменение'},{date:'Сейчас',label:'Следующий шаг'}]; const active=Math.min(rows.length-1,Math.floor(frame/Math.max(1,fps*1.5)));
 return <ThreeOverlay props={props} title={text(p.title,'КОРИДОР ВЕХ')} meta="MILESTONE CORRIDOR" fallback="ring"><div style={{alignSelf:'stretch',display:'flex',gap:8,marginBottom:Math.round(height*.015),overflow:'hidden'}}>{rows.map((milestone,i)=><SafeFlex key={i} style={{padding:'8px 7px',borderRadius:10,background:i===active?`${accent}DD`:`${theme.bg}CC`,color:i===active?theme.bg:theme.text,minWidth:0}}><div style={{fontFamily:fonts.display,fontWeight:900,fontSize:Math.round(height*.014),whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{text(milestone.date,`${i+1}`)}</div><div style={{fontFamily:fonts.body,fontSize:Math.round(height*.012),marginTop:2,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{text(milestone.label)}</div></SafeFlex>)}</div></ThreeOverlay>; };
