import React from 'react';
import {interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {BaseSceneProps} from '../VideoSpec.schema';
import {resolveMotion} from '../lib/motion';
import {fitOneLine, fitWrapped} from '../theme/layout';
import {useStyle} from '../theme/StyleContext';
import {asNumber, asRows, asText, clamp01, SafeFlex, SafeRow, SceneFrame, sceneHeadingStyle} from './expansion_shared';

type Props = BaseSceneProps & Record<string, unknown>;
const pct = (n: number) => `${Math.round(Math.max(0, Math.min(1, n)) * 100)}%`;
const maxOf = (rows: Record<string, unknown>[], key = 'value') => Math.max(1, ...rows.map((row) => asNumber(row[key], 0)));
const read = (value: unknown, fallback = '') => asText(value, fallback);

const Header: React.FC<{eyebrow?: string; title: string; caption?: string}> = ({eyebrow = 'ANALYSIS', title, caption}) => {
  const {height} = useVideoConfig(); const {theme, fonts, accent} = useStyle();
  return <div style={{minWidth: 0}}>
    <div style={{fontFamily: fonts.display, color: accent, fontWeight: 900, fontSize: Math.round(height * .017), letterSpacing: 1.8}}>{eyebrow}</div>
    <div style={{...sceneHeadingStyle(height, fonts, theme.text), marginTop: 7}}>{title}</div>
    {caption && <div style={{fontFamily: fonts.body, color: theme.muted, fontWeight: 650, fontSize: Math.round(height * .018), lineHeight: 1.25, marginTop: 8, maxWidth: '92%'}}>{caption}</div>}
  </div>;
};

const Enter: React.FC<{props: BaseSceneProps; delay?: number; children: React.ReactNode; style?: React.CSSProperties}> = ({props, delay = 0, children, style}) => {
  const frame = useCurrentFrame(); const {fps, height} = useVideoConfig(); const p = clamp01(resolveMotion(props.motion ?? 'reveal', fps, 'reveal')(frame - delay, 0, 1));
  return <div style={{opacity: p, transform: `translateY(${Math.round((1 - p) * height * .024)}px)`, ...style}}>{children}</div>;
};

/** 01 — Head-to-head model arena. */
export const BenchmarkArena: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {width, height} = useVideoConfig(); const {theme, fonts, accent} = useStyle();
  const models = asRows(p.models).slice(0, 4); const rows = models.length ? models : [{name: 'Model A', score: 91}, {name: 'Model B', score: 87}]; const best = maxOf(rows, 'score');
  return <SceneFrame props={props}><Header eyebrow={read(p.benchmark, 'BENCHMARK ARENA')} title={read(p.title, 'СРАВНЕНИЕ МОДЕЛЕЙ')} caption={read(p.source)}/><SafeRow gap={Math.round(width * .022)} style={{marginTop: Math.round(height * .05), alignItems: 'stretch'}}>{rows.map((model, index) => { const score = asNumber(model.score, asNumber(model.value, 0)); const name = read(model.name, `Модель ${index + 1}`); const winner = score === best; const fit = fitWrapped({text: name, maxWidth: width * .16, maxLines: 2, fontFamily: fonts.display, fontWeight: 900, maxFontSize: Math.round(height * .027), minFontSize: Math.round(height * .017)}); return <SafeFlex key={`${name}-${index}`} style={{borderRadius: 22, border: `1.5px solid ${winner ? accent : `${theme.muted}55`}`, background: winner ? `${accent}16` : `${theme.surface}E8`, padding: Math.round(width * .025)}}><Enter props={props} delay={index * 7}><div style={{fontFamily: fonts.display, color: winner ? accent : theme.muted, fontSize: Math.round(height * .015), fontWeight: 900}}>#{index + 1}</div><div style={{fontFamily: fonts.display, color: theme.text, fontSize: fit.fontSize, lineHeight: 1.02, fontWeight: 900, marginTop: 8}}>{name}</div><div style={{fontFamily: fonts.display, color: theme.text, fontSize: Math.round(height * .055), fontWeight: 900, marginTop: Math.round(height * .05)}}>{score}</div><div style={{height: 6, background: `${theme.muted}33`, borderRadius: 99, overflow: 'hidden', marginTop: 12}}><div style={{height: '100%', width: `${Math.round(score / best * 100)}%`, background: winner ? accent : theme.muted, borderRadius: 99}}/></div></Enter></SafeFlex>;})}</SafeRow></SceneFrame>;
};

/** 02 — Models × tests matrix. */
export const BenchmarkHeatmap: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {width, height} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const rows = asRows(p.rows).slice(0, 5); const columns = Array.isArray(p.columns) ? p.columns.filter((x): x is string => typeof x === 'string').slice(0, 4) : ['Код', 'Reasoning', 'Vision']; const table = rows.length ? rows : [{label: 'Model A', values: [91, 88, 83]}, {label: 'Model B', values: [87, 92, 79]}, {label: 'Model C', values: [84, 80, 90]}];
  return <SceneFrame props={props}><Header eyebrow={read(p.source, 'BENCHMARK MATRIX')} title={read(p.title, 'ТЕПЛОВАЯ КАРТА')} /><div style={{marginTop: Math.round(height * .04), borderRadius: 22, border: `1px solid ${theme.muted}55`, overflow: 'hidden', background: `${theme.surface}DD`}}><div style={{display: 'grid', gridTemplateColumns: `minmax(0,1.3fr) repeat(${columns.length}, minmax(0,1fr))`, gap: 1, background: `${theme.muted}33`}}><div style={{padding: 12, background: theme.bg}}/>{columns.map((column) => <div key={column} style={{padding: 12, minWidth: 0, background: theme.bg, fontFamily: fonts.display, color: theme.muted, fontSize: Math.round(height * .014), fontWeight: 900, textAlign: 'center', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap'}}>{column}</div>)}{table.map((row, rowIndex) => { const label = read(row.label, read(row.name, `Model ${rowIndex + 1}`)); const values = Array.isArray(row.values) ? row.values : []; return <React.Fragment key={label}><div style={{padding: 12, minWidth: 0, background: theme.surface, fontFamily: fonts.display, color: theme.text, fontSize: Math.round(height * .018), fontWeight: 850, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap'}}>{label}</div>{columns.map((_, colIndex) => { const value = asNumber(values[colIndex], 0); const fill = value / 100; return <div key={colIndex} style={{padding: 12, minWidth: 0, background: `color-mix(in srgb, ${accent} ${Math.round(12 + fill * 72)}%, ${theme.bg})`, fontFamily: fonts.display, color: fill > .55 ? theme.bg : theme.text, fontWeight: 900, textAlign: 'center', fontSize: Math.round(height * .017)}}>{value}</div>; })}</React.Fragment>; })}</div></div></SceneFrame>;
};

/** 03 — Transparent rank change list. */
export const LeaderboardRace: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {height, width} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const after = asRows(p.rankAfter).slice(0, 5); const before = asRows(p.rankBefore); const rows = after.length ? after : [{name: 'Model A', score: 93}, {name: 'Model B', score: 89}, {name: 'Model C', score: 85}];
  return <SceneFrame props={props}><Header eyebrow={read(p.metric, 'РЕЙТИНГ')} title={read(p.title, 'КАК ИЗМЕНИЛИСЬ МЕСТА')} caption={read(p.asOf)}/><div style={{marginTop: Math.round(height * .04), display: 'flex', flexDirection: 'column', gap: Math.round(height * .012)}}>{rows.map((row, index) => { const name = read(row.name, `Модель ${index + 1}`); const previous = before.find((item) => read(item.name) === name); const oldRank = previous ? before.indexOf(previous) + 1 : index + 1; const delta = oldRank - (index + 1); return <Enter key={name} props={props} delay={index * 7}><SafeRow gap={Math.round(width * .024)} style={{alignItems: 'center', padding: `${Math.round(height * .014)}px ${Math.round(width * .025)}px`, borderRadius: 18, background: index === 0 ? `${accent}14` : `${theme.surface}D8`, border: `1px solid ${index === 0 ? accent : `${theme.muted}44`}`}}><div style={{width: 28, fontFamily: fonts.display, color: index === 0 ? accent : theme.muted, fontWeight: 900, fontSize: Math.round(height * .024)}}>{index + 1}</div><SafeFlex style={{fontFamily: fonts.display, color: theme.text, fontSize: Math.round(height * .023), fontWeight: 850, whiteSpace: 'nowrap', textOverflow: 'ellipsis'}}>{name}</SafeFlex><div style={{fontFamily: fonts.display, color: delta > 0 ? accent : delta < 0 ? '#FF8895' : theme.muted, fontSize: Math.round(height * .017), fontWeight: 900}}>{delta > 0 ? `↑ ${delta}` : delta < 0 ? `↓ ${Math.abs(delta)}` : '—'}</div><div style={{fontFamily: fonts.display, color: theme.text, fontSize: Math.round(height * .021), fontWeight: 900}}>{asNumber(row.score, asNumber(row.value, 0))}</div></SafeRow></Enter>; })}</div></SceneFrame>;
};

/** 04 — Truthful cost/quality scatter. */
export const CostQualityScatter: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {width, height} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const points = asRows(p.scatterPoints).slice(0, 8); const rows = points.length ? points : [{label: 'Эконом', x: 2, y: 74}, {label: 'Баланс', x: 5, y: 87}, {label: 'Топ', x: 12, y: 93}]; const maxX = Math.max(1, ...rows.map((point) => asNumber(point.x, 0))); const maxY = Math.max(1, ...rows.map((point) => asNumber(point.y, 0))); const chartW = width * .82; const chartH = height * .43;
  return <SceneFrame props={props}><Header eyebrow={read(p.source, 'СРАВНЕНИЕ')} title={read(p.title, 'ЦЕНА И КАЧЕСТВО')} caption={`${read(p.xLabel, 'Цена')} × ${read(p.yLabel, 'Качество')}`}/><div style={{width: chartW, height: chartH, marginTop: Math.round(height * .04), position: 'relative', borderLeft: `2px solid ${theme.muted}`, borderBottom: `2px solid ${theme.muted}`}}>{[.25, .5, .75].map((line) => <React.Fragment key={line}><div style={{position: 'absolute', left: 0, right: 0, top: `${line * 100}%`, borderTop: `1px dashed ${theme.muted}44`}}/><div style={{position: 'absolute', top: 0, bottom: 0, left: `${line * 100}%`, borderLeft: `1px dashed ${theme.muted}2D`}}/></React.Fragment>)}{rows.map((point, index) => { const x = asNumber(point.x) / maxX; const y = asNumber(point.y) / maxY; const label = read(point.label, `Точка ${index + 1}`); return <Enter key={label} props={props} delay={index * 6} style={{position: 'absolute', left: `calc(${pct(x)} - 14px)`, bottom: `calc(${pct(y)} - 14px)`}}><div style={{width: 28, height: 28, borderRadius: '50%', background: index === 1 ? accent : theme.cyan, border: `3px solid ${theme.bg}`, boxShadow: `0 0 14px ${index === 1 ? accent : theme.cyan}`}}/><div style={{position: 'absolute', left: 16, bottom: 20, width: Math.round(width * .19), fontFamily: fonts.display, color: theme.text, fontSize: Math.round(height * .014), fontWeight: 850, lineHeight: 1.05}}>{label}</div></Enter>; })}</div></SceneFrame>;
};

/** 05 — Polygon comparison chart. */
export const CapabilityRadar: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {width, height} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const axes = Array.isArray(p.axes) ? p.axes.filter((x): x is string => typeof x === 'string').slice(0, 7) : ['Reasoning', 'Код', 'Vision', 'Latency', 'Контекст']; const series = asRows(p.series).slice(0, 2); const data = series.length ? series : [{label: 'Model A', values: [90, 88, 75, 80, 92]}, {label: 'Model B', values: [82, 91, 86, 89, 78]}]; const size = Math.round(Math.min(width, height) * .54); const cx = size / 2; const radius = size * .35; const pointFor = (i: number, value: number) => { const angle = -Math.PI / 2 + i * Math.PI * 2 / axes.length; const r = radius * value / 100; return `${cx + Math.cos(angle) * r},${cx + Math.sin(angle) * r}`; };
  return <SceneFrame props={props}><Header eyebrow={read(p.source, 'ПРОФИЛЬ ВОЗМОЖНОСТЕЙ')} title={read(p.title, 'ГДЕ СИЛЬНЕЕ МОДЕЛЬ')} /><div style={{width: size, height: size, alignSelf: 'center', marginTop: Math.round(height * .025), position: 'relative'}}><svg width={size} height={size}>{[.25, .5, .75, 1].map((level) => <polygon key={level} points={axes.map((_, i) => pointFor(i, level * 100)).join(' ')} fill="none" stroke={`${theme.muted}44`} strokeWidth="1"/>)}{axes.map((_, i) => <line key={i} x1={cx} y1={cx} x2={Number(pointFor(i, 100).split(',')[0])} y2={Number(pointFor(i, 100).split(',')[1])} stroke={`${theme.muted}55`} />)}{data.map((item, index) => { const values = Array.isArray(item.values) ? item.values : []; return <polygon key={read(item.label, String(index))} points={axes.map((_, i) => pointFor(i, asNumber(values[i], 0))).join(' ')} fill={`${index === 0 ? accent : theme.cyan}33`} stroke={index === 0 ? accent : theme.cyan} strokeWidth="3"/>; })}</svg>{axes.map((axis, i) => { const angle = -Math.PI / 2 + i * Math.PI * 2 / axes.length; return <div key={axis} style={{position: 'absolute', left: cx + Math.cos(angle) * radius * 1.24, top: cx + Math.sin(angle) * radius * 1.24, transform: 'translate(-50%,-50%)', width: 100, textAlign: 'center', fontFamily: fonts.display, color: theme.text, fontWeight: 800, fontSize: Math.round(height * .014), lineHeight: 1.05}}>{axis}</div>; })}</div></SceneFrame>;
};

/** 06 — Context capacity ladder. */
export const ContextWindowLadder: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {height, width} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const items = asRows(p.items).slice(0, 5); const rows = items.length ? items : [{model: 'Базовый', value: 32, caption: 'короткий документ'}, {model: 'Рабочий', value: 128, caption: 'папка файлов'}, {model: 'Длинный', value: 256, caption: 'большой анализ'}]; const max = maxOf(rows);
  return <SceneFrame props={props}><Header eyebrow={read(p.unit, 'КОНТЕКСТ')} title={read(p.title, 'ЛЕСТНИЦА КОНТЕКСТА')} caption={read(p.asOf)}/><div style={{marginTop: Math.round(height * .04), display: 'flex', flexDirection: 'column', gap: Math.round(height * .018)}}>{rows.map((row, index) => { const value = asNumber(row.value); return <Enter key={`${read(row.model)}-${index}`} props={props} delay={index * 6}><div style={{display: 'flex', alignItems: 'center', gap: Math.round(width * .025)}}><div style={{width: Math.round(width * .22), fontFamily: fonts.display, color: theme.text, fontWeight: 850, fontSize: Math.round(height * .019), overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis'}}>{read(row.model, `Уровень ${index + 1}`)}</div><SafeFlex><div style={{height: Math.round(height * .052), borderRadius: 14, background: `${theme.muted}25`, overflow: 'hidden', position: 'relative'}}><div style={{height: '100%', width: `${value / max * 100}%`, minWidth: 48, background: index === rows.length - 1 ? accent : theme.cyan, borderRadius: 14, display: 'flex', alignItems: 'center', paddingLeft: 12, boxSizing: 'border-box', fontFamily: fonts.display, color: theme.bg, fontWeight: 900, fontSize: Math.round(height * .019)}}>{value}K</div></div><div style={{fontFamily: fonts.body, color: theme.muted, fontSize: Math.round(height * .015), marginTop: 4}}>{read(row.caption)}</div></SafeFlex></div></Enter>; })}</div></SceneFrame>;
};

/** 07 — Transparent workload cost split. */
export const TrueCostCalculator: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {height, width} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const lines = asRows(p.lineItems).slice(0, 6); const rows = lines.length ? lines : [{label: 'Входные токены', value: 2.1}, {label: 'Выходные токены', value: 3.4}, {label: 'Кэш', value: 0.8}, {label: 'Повторы', value: 0.5}]; const total = asNumber(p.total, rows.reduce((sum, row) => sum + asNumber(row.value), 0));
  return <SceneFrame props={props}><Header eyebrow={read(p.method, 'WORKLOAD COST')} title={read(p.title, 'ПОЛНАЯ СТОИМОСТЬ')} caption={read(p.currency, 'USD за сценарий')}/><div style={{marginTop: Math.round(height * .04), borderRadius: 24, background: `${theme.surface}E8`, border: `1px solid ${accent}66`, padding: Math.round(width * .04)}}>{rows.map((row, index) => <Enter key={`${read(row.label)}-${index}`} props={props} delay={index * 5}><SafeRow gap={12} style={{alignItems: 'center', padding: `${Math.round(height * .011)}px 0`, borderBottom: index < rows.length - 1 ? `1px solid ${theme.muted}33` : undefined}}><SafeFlex style={{fontFamily: fonts.body, color: theme.text, fontWeight: 700, fontSize: Math.round(height * .021)}}>{read(row.label, `Статья ${index + 1}`)}</SafeFlex><div style={{fontFamily: fonts.display, color: index === rows.length - 1 ? accent : theme.text, fontWeight: 900, fontSize: Math.round(height * .024)}}>{asNumber(row.value).toFixed(2)}</div></SafeRow></Enter>)}<SafeRow gap={12} style={{paddingTop: Math.round(height * .022), alignItems: 'baseline'}}><SafeFlex style={{fontFamily: fonts.display, color: accent, fontWeight: 900, fontSize: Math.round(height * .021)}}>ИТОГО</SafeFlex><div style={{fontFamily: fonts.display, color: theme.text, fontWeight: 900, fontSize: Math.round(height * .052)}}>{total.toFixed(2)}</div></SafeRow></div></SceneFrame>;
};

/** 08 — Token flow with value-preserving links. */
export const TokenFlowSankey: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {height, width} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const nodes = asRows(p.flowNodes).slice(0, 5); const rows = nodes.length ? nodes : [{label: 'Вход', value: 100}, {label: 'Кэш', value: 45}, {label: 'Выход', value: 28}]; const max = maxOf(rows); const links = asRows(p.links);
  return <SceneFrame props={props}><Header eyebrow={read(p.unit, 'TOKEN FLOW')} title={read(p.title, 'КУДА УХОДЯТ ТОКЕНЫ')} caption={read(p.source)}/><div style={{marginTop: Math.round(height * .045), display: 'flex', flexDirection: 'column', gap: Math.round(height * .024)}}>{rows.map((row, index) => { const value = asNumber(row.value); return <Enter key={`${read(row.label)}-${index}`} props={props} delay={index * 7}><SafeRow gap={Math.round(width * .025)} style={{alignItems: 'center'}}><div style={{width: Math.round(width * .20), fontFamily: fonts.display, color: theme.text, fontWeight: 850, fontSize: Math.round(height * .019)}}>{read(row.label, `Узел ${index + 1}`)}</div><SafeFlex><div style={{height: Math.round(height * .05), background: `${theme.muted}26`, borderRadius: 12, overflow: 'hidden'}}><div style={{height: '100%', width: `${value / max * 100}%`, minWidth: 30, borderRadius: 12, background: index === 1 ? accent : theme.cyan, display: 'flex', justifyContent: 'flex-end', alignItems: 'center', paddingRight: 10, boxSizing: 'border-box', fontFamily: fonts.display, color: theme.bg, fontWeight: 900, fontSize: Math.round(height * .017)}}>{value}</div></div></SafeFlex></SafeRow>{index < rows.length - 1 && <div style={{height: Math.round(height * .018), marginLeft: Math.round(width * .24), borderLeft: `2px solid ${links.length ? accent : theme.muted}`}}/>}</Enter>; })}</div></SceneFrame>;
};

/** 09 — Claim → evidence → caveat sequence. */
export const ClaimEvidenceChain: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {height, width} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const evidence = asRows(p.evidence).slice(0, 3); const rows = evidence.length ? evidence : [{label: 'Первичный источник', text: 'Официальное заявление'}, {label: 'Данные', text: 'Число с датой'}, {label: 'Ограничение', text: 'Что ещё нужно проверить'}]; const claim = read(p.claim, read(p.title, 'КАКОЙ ТЕЗИС МЫ ПРОВЕРЯЕМ?'));
  return <SceneFrame props={props}><Header eyebrow="CLAIM → EVIDENCE" title={claim} /><div style={{marginTop: Math.round(height * .04), display: 'flex', flexDirection: 'column', gap: Math.round(height * .018)}}>{rows.map((row, index) => { return <React.Fragment key={`${read(row.label)}-${index}`}><Enter props={props} delay={index * 8}><SafeRow gap={Math.round(width * .025)} style={{alignItems: 'flex-start', padding: Math.round(width * .025), borderRadius: 18, background: index === rows.length - 1 ? `${accent}14` : `${theme.surface}E8`, border: `1px solid ${index === rows.length - 1 ? accent : `${theme.muted}44`}`}}><div style={{width: 28, height: 28, flexShrink: 0, borderRadius: '50%', background: index === rows.length - 1 ? accent : theme.muted, color: theme.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: fonts.display, fontWeight: 900}}>{index + 1}</div><SafeFlex><div style={{fontFamily: fonts.display, color: index === rows.length - 1 ? accent : theme.text, fontWeight: 900, fontSize: Math.round(height * .018)}}>{read(row.label, `Шаг ${index + 1}`)}</div><div style={{fontFamily: fonts.body, color: theme.muted, fontWeight: 650, fontSize: Math.round(height * .018), marginTop: 5, lineHeight: 1.18}}>{read(row.text, read(row.detail))}</div></SafeFlex></SafeRow></Enter>{index < rows.length - 1 && <div style={{height: 15, marginLeft: 26, borderLeft: `2px solid ${accent}88`}}/>}</React.Fragment>; })}</div>{read(p.caveat) && <div style={{fontFamily: fonts.body, color: theme.muted, fontSize: Math.round(height * .017), marginTop: Math.round(height * .03)}}>Ограничение: {read(p.caveat)}</div>}</SceneFrame>;
};

/** 10 — Evidence disagreement board. */
export const EvidenceConflictBoard: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {width, height} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const claim = read(p.claim, read(p.title, 'ИСТОЧНИКИ РАСХОДЯТСЯ'));
  const card = (item: unknown, side: string, active: boolean) => { const row = typeof item === 'object' && item ? item as Record<string, unknown> : {}; const headline = read(row.title, read(row.name, side)); const detail = read(row.detail, read(row.text, 'Нужна проверка даты и методологии')); const fit = fitWrapped({text: headline, maxWidth: width * .30, maxLines: 3, fontFamily: fonts.display, fontWeight: 900, maxFontSize: Math.round(height * .028), minFontSize: Math.round(height * .017)}); return <SafeFlex style={{padding: Math.round(width * .03), borderRadius: 20, border: `1px solid ${active ? accent : `${theme.muted}55`}`, background: active ? `${accent}12` : `${theme.surface}DD`}}><div style={{fontFamily: fonts.display, color: active ? accent : theme.muted, fontWeight: 900, fontSize: Math.round(height * .015)}}>{side}</div><div style={{fontFamily: fonts.display, color: theme.text, fontSize: fit.fontSize, fontWeight: 900, lineHeight: 1.05, marginTop: 9}}>{headline}</div><div style={{fontFamily: fonts.body, color: theme.muted, fontSize: Math.round(height * .016), lineHeight: 1.2, marginTop: 10}}>{detail}</div></SafeFlex>; };
  return <SceneFrame props={props}><Header eyebrow="CONFLICT CHECK" title={claim} /><SafeRow gap={Math.round(width * .026)} style={{marginTop: Math.round(height * .045)}}>{card(p.sourceA, 'ИСТОЧНИК A', false)}{card(p.sourceB, 'ИСТОЧНИК B', true)}</SafeRow><div style={{marginTop: Math.round(height * .03), borderRadius: 16, padding: Math.round(width * .026), background: `${theme.muted}17`, fontFamily: fonts.body, color: theme.text, fontSize: Math.round(height * .018), lineHeight: 1.22}}><b style={{color: accent}}>Различие:</b> {read(p.difference, 'Сверьте дату, выборку и определение метрики.')}</div></SceneFrame>;
};

/** 11 — Reproducible test protocol. */
export const ExperimentProtocol: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {height, width} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const steps = asRows(p.steps).slice(0, 5); const rows = steps.length ? steps : [{label: 'Dataset', detail: 'Один и тот же набор задач'}, {label: 'Настройки', detail: 'Одинаковый prompt и temperature'}, {label: 'Метрика', detail: 'Качество, цена и latency'}];
  return <SceneFrame props={props}><Header eyebrow={read(p.metric, 'EXPERIMENT PROTOCOL')} title={read(p.title, 'КАК ПОВТОРИТЬ ТЕСТ')} caption={read(p.threshold)}/><div style={{marginTop: Math.round(height * .04), display: 'flex', flexDirection: 'column', gap: Math.round(height * .016)}}>{rows.map((row, index) => <Enter key={`${read(row.label)}-${index}`} props={props} delay={index * 7}><SafeRow gap={Math.round(width * .022)} style={{padding: Math.round(width * .025), borderRadius: 18, border: `1px solid ${theme.muted}44`, background: `${theme.surface}D8`, alignItems: 'center'}}><div style={{fontFamily: fonts.display, color: accent, fontWeight: 900, fontSize: Math.round(height * .026)}}>{String(index + 1).padStart(2, '0')}</div><SafeFlex><div style={{fontFamily: fonts.display, color: theme.text, fontWeight: 900, fontSize: Math.round(height * .019)}}>{read(row.label, `Шаг ${index + 1}`)}</div><div style={{fontFamily: fonts.body, color: theme.muted, fontSize: Math.round(height * .016), marginTop: 3}}>{read(row.detail, read(row.text))}</div></SafeFlex></SafeRow></Enter>)}</div></SceneFrame>;
};

/** 12 — Version-to-version change set. */
export const ReleaseDelta: React.FC<BaseSceneProps> = (props) => {
  const p = props as Props; const {height, width} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); const deltas = asRows(p.deltas).slice(0, 5); const rows = deltas.length ? deltas : [{kind: 'ДОБАВЛЕНО', text: 'Новый режим'}, {kind: 'ИЗМЕНЕНО', text: 'Обновлён лимит'}, {kind: 'ПРОВЕРИТЬ', text: 'Цена и дата вступления'}];
  return <SceneFrame props={props}><Header eyebrow="RELEASE DELTA" title={read(p.title, 'ЧТО ИЗМЕНИЛОСЬ')} caption={`${read(p.previous, 'Предыдущая версия')} → ${read(p.current, 'Текущая версия')}`}/><div style={{marginTop: Math.round(height * .04), display: 'flex', flexDirection: 'column', gap: Math.round(height * .014)}}>{rows.map((row, index) => { const kind = read(row.kind, index === 0 ? 'ДОБАВЛЕНО' : 'ИЗМЕНЕНО'); const color = /убра|risk|пров/i.test(kind) ? '#FF8895' : kind.includes('ДОБ') ? accent : theme.cyan; return <Enter key={`${kind}-${index}`} props={props} delay={index * 6}><SafeRow gap={Math.round(width * .025)} style={{alignItems: 'center', padding: `${Math.round(height * .015)}px ${Math.round(width * .026)}px`, borderRadius: 16, background: `${theme.surface}DD`, borderLeft: `5px solid ${color}`}}><div style={{width: Math.round(width * .20), flexShrink: 0, fontFamily: fonts.display, color, fontSize: Math.round(height * .014), fontWeight: 900}}>{kind}</div><SafeFlex style={{fontFamily: fonts.body, color: theme.text, fontSize: Math.round(height * .019), fontWeight: 700}}>{read(row.text, read(row.detail))}</SafeFlex></SafeRow></Enter>; })}</div></SceneFrame>;
};
