import React from 'react';
import {interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {BaseSceneProps} from '../VideoSpec.schema';
import {resolveMotion} from '../lib/motion';
import {fitOneLine, fitWrapped} from '../theme/layout';
import {useStyle} from '../theme/StyleContext';
import {asNumber, asRows, asText, clamp01, SafeFlex, SafeRow, SceneFrame, sceneHeadingStyle} from './expansion_shared';

type Props = BaseSceneProps & Record<string, unknown>;
const text=(v:unknown,f='')=>asText(v,f);
const Header:React.FC<{title:string;meta?:string;caption?:string}>=({title,meta='NARRATIVE',caption})=>{const {height}=useVideoConfig();const {theme,fonts,accent}=useStyle();return <><div style={{fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.017),letterSpacing:1.8}}>{meta}</div><div style={{...sceneHeadingStyle(height,fonts,theme.text),marginTop:7}}>{title}</div>{caption&&<div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.018),lineHeight:1.2,marginTop:8}}>{caption}</div>}</>};
const In:React.FC<{props:BaseSceneProps;delay?:number;children:React.ReactNode;style?:React.CSSProperties}>=({props,delay=0,children,style})=>{const f=useCurrentFrame();const {fps,height}=useVideoConfig();const q=clamp01(resolveMotion(props.motion??'reveal',fps,'reveal')(f-delay,0,1));return <div style={{opacity:q,transform:`translateY(${Math.round((1-q)*height*.025)}px)`,...style}}>{children}</div>;};

/** 43 — Strong contradiction resolves into the real question. */
export const ColdOpenContradiction:React.FC<BaseSceneProps>=(props)=>{const p=props as Props;const f=useCurrentFrame();const {width,height,fps}=useVideoConfig();const {theme,fonts,accent}=useStyle();const a=text(p.claimA,'МОДЕЛЬ ДЕШЕВЛЕ');const b=text(p.claimB,'МОДЕЛЬ ЛУЧШЕ');const question=text(p.realQuestion,'КАКАЯ МЕТРИКА НУЖНА ИМЕННО ВАШЕЙ ЗАДАЧЕ?');const reveal=clamp01(resolveMotion(props.motion??'reveal',fps,'reveal')(f-Math.round(fps*.65),0,1));const card=(copy:string,side:'left'|'right')=>{const fit=fitWrapped({text:copy,maxWidth:width*.34,maxLines:3,fontFamily:fonts.display,fontWeight:900,maxFontSize:Math.round(height*.042),minFontSize:Math.round(height*.022),lineHeight:.98});return <SafeFlex style={{padding:Math.round(width*.03),borderRadius:20,background:side==='left'?`${theme.muted}24`:`${accent}19`,border:`1px solid ${side==='left'?theme.muted:accent}`}}><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:fit.fontSize,lineHeight:.98}}>{copy}</div></SafeFlex>};return <SceneFrame props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center'}}><div style={{fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.017),letterSpacing:2}}>СТОП-СКРОЛЛ</div><SafeRow gap={Math.round(width*.025)} style={{marginTop:Math.round(height*.025)}}>{card(a,'left')}<div style={{alignSelf:'center',fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.034)}}>×</div>{card(b,'right')}</SafeRow><In props={props} delay={Math.round(fps*.65)}><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:fitWrapped({text:question,maxWidth:width*.78,maxLines:4,fontFamily:fonts.display,fontWeight:900,maxFontSize:Math.round(height*.043),minFontSize:Math.round(height*.024)}).fontSize,lineHeight:1.03,marginTop:Math.round(height*.055)}}>{question}</div></In></div></SceneFrame>;};

/** 44 — Outcome split for decision scenarios. */
export const CounterfactualSplit:React.FC<BaseSceneProps>=(props)=>{const p=props as Props;const {width,height}=useVideoConfig();const {theme,fonts,accent}=useStyle();const card=(choice:string,outcomes:unknown,active:boolean)=>{const list=Array.isArray(outcomes)?outcomes.filter((x):x is string=>typeof x==='string').slice(0,4):[];return <SafeFlex style={{padding:Math.round(width*.03),borderRadius:22,background:active?`${accent}16`:`${theme.surface}E8`,border:`1px solid ${active?accent:`${theme.muted}44`}`}}><div style={{fontFamily:fonts.display,color:active?accent:theme.muted,fontWeight:900,fontSize:Math.round(height*.016)}}>ЕСЛИ ВЫБРАТЬ</div><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.028),lineHeight:1.05,marginTop:7}}>{choice}</div><div style={{marginTop:Math.round(height*.03),display:'flex',flexDirection:'column',gap:8}}>{(list.length?list:['Первое последствие','Второе последствие']).map((item,i)=><SafeRow key={i} gap={8} style={{alignItems:'flex-start'}}><span style={{color:active?accent:theme.muted}}>•</span><SafeFlex style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.017),lineHeight:1.18}}>{item}</SafeFlex></SafeRow>)}</div></SafeFlex>};return <SceneFrame props={props}><Header meta="CHOICE OUTCOME" title={text(p.title,'ДВЕ РАЗВИЛКИ — РАЗНЫЕ ПОСЛЕДСТВИЯ')}/><SafeRow gap={Math.round(width*.025)} style={{marginTop:Math.round(height*.04)}}>{card(text(p.choiceA,'Вариант A'),p.outcomesA,false)}{card(text(p.choiceB,'Вариант B'),p.outcomesB,true)}</SafeRow></SceneFrame>;};

/** 45 — Past, present, next memory fragments. */
export const MemoryTimeline:React.FC<BaseSceneProps>=(props)=>{const p=props as Props;const f=useCurrentFrame();const {height,width,fps}=useVideoConfig();const {theme,fonts,accent}=useStyle();const items=[['ТОГДА',text(p.past,'Пробовали наугад')],['СЕЙЧАС',text(p.present,'Проверяем по источникам')],['ДАЛЬШЕ',text(p.next,'Собираем свой workflow')]];const active=Math.min(2,Math.floor(f/Math.max(1,fps*1.3)));return <SceneFrame props={props}><Header meta="MEMORY TIMELINE" title={text(p.title,'КАК СОБРАЛАСЬ ИСТОРИЯ')} /><div style={{marginTop:Math.round(height*.05),display:'flex',flexDirection:'column',gap:Math.round(height*.023)}}>{items.map(([label,copy],i)=><In key={label} props={props} delay={i*7}><SafeRow gap={Math.round(width*.025)} style={{alignItems:'center'}}><div style={{width:Math.round(width*.20),fontFamily:fonts.display,color:i===active?accent:theme.muted,fontWeight:900,fontSize:Math.round(height*.017)}}>{label}</div><SafeFlex style={{borderRadius:16,padding:Math.round(width*.025),background:i===active?`${accent}15`:`${theme.surface}D8`,border:`1px solid ${i===active?accent:`${theme.muted}44`}`,fontFamily:fonts.display,color:theme.text,fontWeight:800,fontSize:Math.round(height*.022),lineHeight:1.12}}>{copy}</SafeFlex></SafeRow></In>)}</div></SceneFrame>;};

/** 46 — Data-defined decision tree. */
export const DecisionTree:React.FC<BaseSceneProps>=(props)=>{const p=props as Props;const {height,width}=useVideoConfig();const {theme,fonts,accent}=useStyle();const nodes=asRows(p.decisionNodes).slice(0,7);const rows=nodes.length?nodes:[{label:'Нужна приватность?',branch:'Да → локально'},{label:'Нужна скорость?',branch:'Да → API'}];const path=Array.isArray(p.chosenPath)?p.chosenPath.filter((x):x is string=>typeof x==='string'):[];return <SceneFrame props={props}><Header meta="DECISION TREE" title={text(p.title,'ВЫБЕРИТЕ ПРАВИЛЬНЫЙ ПУТЬ')}/><div style={{marginTop:Math.round(height*.035),display:'flex',flexDirection:'column',gap:Math.round(height*.015)}}>{rows.map((node,i)=>{const active=path.includes(text(node.id))||i===0;return <React.Fragment key={i}><SafeRow gap={12} style={{alignItems:'center'}}><div style={{width:26,height:26,borderRadius:'50%',background:active?accent:theme.muted,color:theme.bg,fontFamily:fonts.display,fontWeight:900,display:'flex',alignItems:'center',justifyContent:'center'}}>{i+1}</div><SafeFlex style={{padding:Math.round(width*.023),borderRadius:15,background:active?`${accent}16`:`${theme.surface}D8`,border:`1px solid ${active?accent:`${theme.muted}44`}`}}><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.019)}}>{text(node.label,`Вопрос ${i+1}`)}</div><div style={{fontFamily:fonts.body,color:active?accent:theme.muted,fontWeight:700,fontSize:Math.round(height*.016),marginTop:4}}>{text(node.branch,text(node.outcome))}</div></SafeFlex></SafeRow>{i<rows.length-1&&<div style={{height:12,marginLeft:12,borderLeft:`2px solid ${accent}77`}}/>}</React.Fragment>})}</div></SceneFrame>;};

/** 47 — Transparent trade-off sliders. */
export const TradeoffSliders:React.FC<BaseSceneProps>=(props)=>{const p=props as Props;const {height,width}=useVideoConfig();const {theme,fonts,accent}=useStyle();const dimensions=asRows(p.dimensions).slice(0,4);const rows=dimensions.length?dimensions:[{label:'Цена',value:28,left:'дешевле',right:'качественнее'},{label:'Latency',value:64,left:'быстрее',right:'точнее'},{label:'Приватность',value:78,left:'облако',right:'локально'}];return <SceneFrame props={props}><Header meta="TRADE-OFFS" title={text(p.title,'КОМПРОМИССЫ ВИДНЫ СРАЗУ')} caption={text(p.takeaway)}/><div style={{marginTop:Math.round(height*.04),display:'flex',flexDirection:'column',gap:Math.round(height*.03)}}>{rows.map((row,i)=>{const value=asNumber(row.value,50);return <In key={i} props={props} delay={i*6}><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:850,fontSize:Math.round(height*.019)}}>{text(row.label,`Шкала ${i+1}`)}</div><div style={{height:12,borderRadius:99,background:`${theme.muted}33`,position:'relative',marginTop:8}}><div style={{position:'absolute',left:`${value}%`,top:'50%',width:24,height:24,transform:'translate(-50%,-50%)',borderRadius:'50%',background:accent,border:`3px solid ${theme.bg}`,boxShadow:`0 0 14px ${accent}`}}/></div><SafeRow gap={10} style={{marginTop:7}}><SafeFlex style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.014)}}>{text(row.left)}</SafeFlex><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.014),textAlign:'right'}}>{text(row.right)}</div></SafeRow></In>})}</div></SceneFrame>;};

/** 48 — Date and change-window scene. */
export const CalendarLaunchWindow:React.FC<BaseSceneProps>=(props)=>{const p=props as Props;const {height,width}=useVideoConfig();const {theme,fonts,accent}=useStyle();return <SceneFrame props={props}><Header meta={text(p.timezone,'LAUNCH WINDOW')} title={text(p.title,'ОКНО ЗАПУСКА')} /><div style={{marginTop:Math.round(height*.05),alignSelf:'center',width:width*.62,borderRadius:26,overflow:'hidden',border:`1.5px solid ${accent}`,background:`${theme.surface}EE`,textAlign:'center'}}><div style={{padding:'10px',background:accent,color:theme.bg,fontFamily:fonts.display,fontWeight:900,fontSize:Math.round(height*.018)}}>{text(p.window,'ОКНО ИЗМЕНЕНИЙ')}</div><div style={{padding:Math.round(width*.04)}}><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:fitOneLine({text:text(p.date,'16 AUG'),maxWidth:width*.48,fontFamily:fonts.display,maxFontSize:Math.round(height*.074),minFontSize:Math.round(height*.032)})}}>{text(p.date,'16 AUG')}</div><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.019),lineHeight:1.2,marginTop:12}}>{text(p.whatChanges,'Проверьте, что именно изменится и когда.')}</div></div></div><div style={{fontFamily:fonts.body,color:accent,fontSize:Math.round(height*.016),textAlign:'center',marginTop:Math.round(height*.03)}}>{text(p.source)}</div></SceneFrame>;};

/** 49 — CTA that leads with evidence and useful action. */
export const ProofBackedCTA:React.FC<BaseSceneProps>=(props)=>{const p=props as Props;const {height,width}=useVideoConfig();const {theme,fonts,accent}=useStyle();return <SceneFrame props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center'}}><div style={{fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.017),letterSpacing:2}}>ПРОВЕРЕННЫЙ СЛЕДУЮЩИЙ ШАГ</div><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.047),lineHeight:1.02,marginTop:9,maxWidth:width*.78}}>{text(p.action,text(p.title,'ОТКРОЙТЕ ПОЛНЫЙ РАЗБОР'))}</div><div style={{marginTop:Math.round(height*.04),padding:Math.round(width*.033),borderRadius:22,background:`${theme.surface}E8`,border:`1px solid ${accent}77`}}><div style={{fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.016)}}>ДОКАЗАТЕЛЬСТВО</div><div style={{fontFamily:fonts.body,color:theme.text,fontWeight:700,fontSize:Math.round(height*.021),lineHeight:1.2,marginTop:7}}>{text(p.proof,'Ссылка на первоисточник, дату и метод проверки.')}</div><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.018),lineHeight:1.2,marginTop:13}}>{text(p.benefit,'Получите готовый способ проверить тезис на своей задаче.')}</div></div><div style={{alignSelf:'flex-start',marginTop:Math.round(height*.035),padding:'11px 15px',borderRadius:999,background:accent,color:theme.bg,fontFamily:fonts.display,fontWeight:900,fontSize:Math.round(height*.018)}}>{text(p.channel,'@llm_hubs')} →</div></div></SceneFrame>;};

/** 50 — Three brand motifs resolve into an outro card. */
export const BrandOutroMosaic:React.FC<BaseSceneProps>=(props)=>{const p=props as Props;const f=useCurrentFrame();const {height,width,fps}=useVideoConfig();const {theme,fonts,accent}=useStyle();const media=asRows(p.media).slice(0,3);const rows=media.length?media:[{label:'ПРОДУКТ'},{label:'ДОКАЗАТЕЛЬСТВА'},{label:'КОМЬЮНИТИ'}];const q=clamp01(resolveMotion(props.motion??'reveal',fps,'reveal')(f,0,1));return <SceneFrame props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',textAlign:'center'}}><div style={{display:'flex',gap:Math.round(width*.025),width:'100%',justifyContent:'center'}}>{rows.map((item,i)=><div key={i} style={{width:width*.23,height:height*.16,display:'flex',alignItems:'center',justifyContent:'center',borderRadius:20,background:i===1?`${accent}1B`:`${theme.surface}DD`,border:`1px solid ${i===1?accent:`${theme.muted}44`}`,transform:`translateY(${Math.round((1-q)*(i-1)*height*.08)}px) rotate(${(i-1)*5}deg)`,fontFamily:fonts.display,color:i===1?accent:theme.text,fontSize:Math.round(height*.015),fontWeight:900,padding:10,boxSizing:'border-box'}}>{text(item.label,`МОТИВ ${i+1}`)}</div>)}</div><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.052),lineHeight:1,marginTop:Math.round(height*.05)}}>{text(p.brandName,text(p.title,'ВАШ КАНАЛ'))}</div><div style={{fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.025),marginTop:9}}>{text(p.handle,'@channel')}</div><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.019),marginTop:14}}>{text(p.cta,'Подпишитесь, чтобы не пропустить следующий разбор.')}</div></div></SceneFrame>;};
