import React from 'react';
import {Img, OffthreadVideo, interpolate, useCurrentFrame, useVideoConfig} from 'remotion';
import {BaseSceneProps} from '../VideoSpec.schema';
import {resolveMotion} from '../lib/motion';
import {fitWrapped} from '../theme/layout';
import {useStyle} from '../theme/StyleContext';
import {asNumber, asRows, asText, clamp01, isVideoMedia, resolveMedia, SafeFlex, SafeRow, SceneFrame, sceneHeadingStyle} from './expansion_shared';

type Props = BaseSceneProps & Record<string, unknown>;
const text = (v: unknown, f = '') => asText(v, f);
const Media: React.FC<{url: string; style?: React.CSSProperties; label?: string}> = ({url, style, label = 'MEDIA'}) => { const {theme,fonts,accent}=useStyle(); const source=resolveMedia(url); return <div style={{position:'relative',overflow:'hidden',background:source?theme.bg:`linear-gradient(145deg,${theme.surface},${theme.bg})`,...style}}>{source?(isVideoMedia(source)?<OffthreadVideo src={source} volume={0} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<Img src={source} style={{width:'100%',height:'100%',objectFit:'cover'}}/>):<div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',fontFamily:fonts.display,fontWeight:900,color:accent,letterSpacing:2}}>{label}</div>}</div>; };
const Heading: React.FC<{title:string;meta?:string;caption?:string}> = ({title,meta='MEDIA',caption})=>{const {height}=useVideoConfig();const {theme,fonts,accent}=useStyle();return <><div style={{fontFamily:fonts.display,color:accent,fontSize:Math.round(height*.017),fontWeight:900,letterSpacing:1.7}}>{meta}</div><div style={{...sceneHeadingStyle(height,fonts,theme.text),marginTop:7}}>{title}</div>{caption&&<div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.018),lineHeight:1.2,marginTop:8}}>{caption}</div>}</>};
const In: React.FC<{props:BaseSceneProps;delay?:number;children:React.ReactNode;style?:React.CSSProperties}> = ({props,delay=0,children,style})=>{const f=useCurrentFrame();const {fps,height}=useVideoConfig();const q=clamp01(resolveMotion(props.motion??'reveal',fps,'reveal')(f-delay,0,1));return <div style={{opacity:q,transform:`translateY(${Math.round((1-q)*height*.022)}px)`,...style}}>{children}</div>;};

/** 23 — Slow interpolated flight across three arbitrarily placed photos. */
export const ThreePhoto360Drift: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,durationInFrames}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const images=Array.isArray(p.images)?p.images.filter((x):x is string=>typeof x==='string').slice(0,3):[]; const photos=images.length===3?images:['','','']; const positions=asRows(p.positions); const defaultPositions=[{x:-.28,y:-.12,z:-120,rotate:-12},{x:.22,y:.03,z:0,rotate:8},{x:-.06,y:.18,z:-80,rotate:-6}]; const steps=[0,Math.round(durationInFrames*.42),Math.round(durationInFrames*.78),durationInFrames-1]; const focus=Math.min(2,Math.floor(interpolate(frame,steps,[0,1,2,2],{extrapolateRight:'clamp'}))); const local=interpolate(frame,steps,[0,0,0,1],{extrapolateRight:'clamp'});
 return <SceneFrame props={props}><Heading meta="360° PHOTO DRIFT" title={text(p.title,'ТРИ КАДРА — ОДНА ИСТОРИЯ')} caption={text(p.caption,'Камера медленно проходит по объёмной композиции.')}/><div style={{flex:1,marginTop:Math.round(height*.02),position:'relative',perspective:1200,overflow:'visible'}}>{photos.map((url,i)=>{const item=positions[i]||defaultPositions[i]; const x=asNumber(item.x,defaultPositions[i].x)*width; const y=asNumber(item.y,defaultPositions[i].y)*height; const z=asNumber(item.z,defaultPositions[i].z); const rotation=asNumber(item.rotate,defaultPositions[i].rotate); const focused=i===focus; const scale=focused?1.08:0.74; return <div key={i} style={{position:'absolute',left:'50%',top:'47%',width:width*.56,height:height*.41,transform:`translate(-50%,-50%) translate3d(${Math.round(x)}px,${Math.round(y)}px,${z}px) rotateZ(${rotation}deg) scale(${scale})`,zIndex:focused?4:i+1,transition:'transform .2s',borderRadius:26,overflow:'hidden',boxShadow:`0 30px 55px ${theme.shadowColor}BB`,border:`2px solid ${focused?accent:`${theme.muted}55`}`}}><Media url={url} style={{width:'100%',height:'100%'}} label={`ФОТО ${i+1}`}/><div style={{position:'absolute',left:14,bottom:13,fontFamily:fonts.display,color:'#fff',fontWeight:900,fontSize:Math.round(height*.016),textShadow:'0 2px 6px #000'}}>{Array.isArray(p.captions)&&typeof p.captions[i]==='string'?p.captions[i]:`Кадр ${i+1}`}</div></div>;})}</div><div style={{fontFamily:fonts.display,color:accent,fontSize:Math.round(height*.016),fontWeight:900,letterSpacing:1}}>КАМЕРА → {focus+1}/3 {local>0?'· ФИНАЛ':' '}</div></SceneFrame>; };

/** 24 — A seeded constellation of photos with focus route. */
export const PhotoConstellation: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,accent}=useStyle(); const images=Array.isArray(p.images)?p.images.filter((x):x is string=>typeof x==='string').slice(0,9):[]; const rows=images.length?images:['','','','']; const order=Array.isArray(p.focusOrder)?p.focusOrder.map((x)=>typeof x==='number'?x:0):[0,1,2]; const focus=order[Math.min(order.length-1,Math.floor(frame/Math.max(1,fps*1.5)))]||0;
 return <SceneFrame props={props}><Heading meta="PHOTO CONSTELLATION" title={text(p.title,'СОЗВЕЗДИЕ КАДРОВ')} /><div style={{position:'relative',flex:1,marginTop:10}}>{rows.map((url,i)=>{const angle=i*Math.PI*2/rows.length-Math.PI/2; const radiusX=width*.30; const radiusY=height*.24; const active=i===focus; return <div key={i} style={{position:'absolute',left:`calc(50% + ${Math.round(Math.cos(angle)*radiusX)}px)`,top:`calc(48% + ${Math.round(Math.sin(angle)*radiusY)}px)`,width:active?width*.40:width*.27,height:active?height*.30:height*.20,transform:`translate(-50%,-50%) rotate(${(i%2?1:-1)*(5+i)}deg)`,zIndex:active?10:i,borderRadius:20,overflow:'hidden',border:`2px solid ${active?accent:`${theme.muted}55`}`,boxShadow:`0 18px 42px ${theme.shadowColor}BB`}}><Media url={url} style={{width:'100%',height:'100%'}} label={`ФОТО ${i+1}`}/></div>;})}</div></SceneFrame>; };

/** 25 — Full image → explicit zoom stops. */
export const DeepZoomStory: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,durationInFrames}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const stops=asRows(p.stops).slice(0,3); const rows=stops.length?stops:[{x:.5,y:.5,scale:1,label:'ОБЩИЙ ВИД'},{x:.7,y:.42,scale:1.65,label:'ВАЖНАЯ ДЕТАЛЬ'}]; const phase=Math.min(rows.length-1,Math.floor(frame/Math.max(1,durationInFrames/rows.length))); const s=rows[phase]; const scale=asNumber(s.scale,1); const x=asNumber(s.x,.5),y=asNumber(s.y,.5);
 return <SceneFrame props={props}><Heading meta="DEEP ZOOM" title={text(p.title,'СМОТРИМ НА ДЕТАЛЬ')} /><div style={{height:height*.55,marginTop:Math.round(height*.04),borderRadius:24,overflow:'hidden',position:'relative',border:`1px solid ${accent}66`,background:theme.surface}}><div style={{position:'absolute',inset:0,transform:`scale(${scale}) translate(${(0.5-x)*100}%,${(0.5-y)*100}%)`,transformOrigin:'50% 50%'}}><Media url={text(p.image,text(p.mediaUrl))} style={{width:'100%',height:'100%'}} label="ИЗОБРАЖЕНИЕ"/></div><div style={{position:'absolute',left:`${x*100}%`,top:`${y*100}%`,width:70,height:70,transform:'translate(-50%,-50%)',border:`3px solid ${accent}`,borderRadius:14,boxShadow:`0 0 0 100vmax ${theme.bg}55,0 0 20px ${accent}`}}/></div><div style={{fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.019),marginTop:13}}>{text(s.label,'ФОКУС')}</div></SceneFrame>; };

/** 26 — Two visual states revealed by a clean split lens. */
export const BeforeAfterLens: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,durationInFrames}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const split=interpolate(frame,[0,durationInFrames-1],[.25,.75],{extrapolateRight:'clamp'});
 return <SceneFrame props={props}><Heading meta="BEFORE / AFTER" title={text(p.claim,text(p.title,'ЧТО ИЗМЕНИЛОСЬ'))}/><div style={{height:height*.52,marginTop:Math.round(height*.04),borderRadius:24,overflow:'hidden',position:'relative',border:`1px solid ${accent}66`}}><Media url={text(p.afterUrl)} style={{position:'absolute',inset:0,width:'100%',height:'100%'}} label="ПОСЛЕ"/><div style={{position:'absolute',inset:0,width:`${split*100}%`,overflow:'hidden'}}><Media url={text(p.beforeUrl)} style={{width:width*.84,height:'100%'}} label="ДО"/></div><div style={{position:'absolute',top:0,bottom:0,left:`${split*100}%`,width:4,background:accent,boxShadow:`0 0 14px ${accent}`}}/><div style={{position:'absolute',left:14,top:14,padding:'6px 9px',borderRadius:999,background:theme.bg,fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.015)}}>{text(p.labelBefore,'ДО')}</div><div style={{position:'absolute',right:14,top:14,padding:'6px 9px',borderRadius:999,background:accent,fontFamily:fonts.display,color:theme.bg,fontWeight:900,fontSize:Math.round(height*.015)}}>{text(p.labelAfter,'ПОСЛЕ')}</div></div></SceneFrame>; };

/** 27 — Video frame with a chapter rail. */
export const VideoChapterRail: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const chapters=asRows(p.chapters).slice(0,5); const rows=chapters.length?chapters:[{label:'Вводная',at:0},{label:'Главный факт',at:15},{label:'Практический шаг',at:30}]; const active=Math.min(rows.length-1,Math.floor(frame/Math.max(1,fps*1.8)));
 return <SceneFrame props={props}><Media url={text(p.videoUrl)} style={{height:height*.38,borderRadius:24,border:`1px solid ${accent}77`}} label="ВИДЕО"/><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.032),marginTop:Math.round(height*.022)}}>{text(p.title,'ВИДЕОРАЗБОР')}</div><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.017),marginTop:4}}>{text(p.channel,'КАНАЛ')}</div><div style={{marginTop:Math.round(height*.03),display:'flex',flexDirection:'column',gap:8}}>{rows.map((r,i)=><SafeRow key={i} gap={10} style={{alignItems:'center'}}><div style={{width:10,height:10,borderRadius:'50%',background:i===active?accent:theme.muted}}/><SafeFlex style={{fontFamily:fonts.display,color:i===active?theme.text:theme.muted,fontWeight:i===active?900:750,fontSize:Math.round(height*.018)}}>{text(r.label,`Глава ${i+1}`)}</SafeFlex><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.015)}}>{text(r.at,'')}</div></SafeRow>)}</div></SceneFrame>; };

/** 28 — Voice message that expands to a pull quote. */
export const VoiceNotePullQuote: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const q=clamp01(resolveMotion(props.motion??'reveal',fps,'reveal')(frame,0,1)); const quote=text(p.quote,text(p.caption,'Сначала источник, потом вывод.')); const bars=Array.from({length:30},(_,i)=>8+((i*13+asNumber(p.waveformSeed,7)*7)%27));
 return <SceneFrame props={props}><div style={{height:'100%',display:'flex',alignItems:'center',justifyContent:'center'}}><In props={props} style={{width:width*.84}}><div style={{borderRadius:26,padding:Math.round(width*.04),background:`${theme.surface}EE`,border:`1px solid ${accent}77`}}><SafeRow gap={12} style={{alignItems:'center'}}><div style={{width:Math.round(height*.06),height:Math.round(height*.06),borderRadius:'50%',background:accent,color:theme.bg,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900}}>▶</div><SafeFlex><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.023)}}>{text(p.speaker,'СПИКЕР')}</div><div style={{height:34,display:'flex',gap:3,alignItems:'center',marginTop:6}}>{bars.map((h,i)=><span key={i} style={{width:4,height:Math.max(3,h*(.6+.4*Math.sin((frame+i)/fps*4))),borderRadius:9,background:i<18?accent:theme.muted}}/>)}</div></SafeFlex><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.016)}}>{text(p.duration,'0:18')}</div></SafeRow><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:850,fontSize:Math.round(height*.027),lineHeight:1.14,marginTop:Math.round(height*.035)}}>“{quote}”</div></div></In></div></SceneFrame>; };

/** 29 — Document with positioned marginal annotations. */
export const DocumentMarginNotes: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {width,height}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const notes=asRows(p.notes).slice(0,3); const rows=notes.length?notes:[{x:.76,y:.28,text:'Проверьте дату'},{x:.70,y:.55,text:'Сравните scope'}];
 return <SceneFrame props={props}><Heading meta={text(p.source,'DOCUMENT REVIEW')} title={text(p.title,'ЗАМЕТКИ НА ПОЛЯХ')} /><div style={{height:height*.55,marginTop:Math.round(height*.035),borderRadius:22,overflow:'hidden',position:'relative',background:theme.surface,border:`1px solid ${theme.muted}55`}}><Media url={text(p.documentUrl)} style={{position:'absolute',inset:0,width:'100%',height:'100%',opacity:.88}} label="ДОКУМЕНТ"/>{rows.map((n,i)=><div key={i} style={{position:'absolute',left:`${asNumber(n.x,.7)*100}%`,top:`${asNumber(n.y,.4)*100}%`,maxWidth:width*.26,padding:'8px 10px',borderRadius:12,background:accent,color:theme.bg,fontFamily:fonts.display,fontWeight:900,fontSize:Math.round(height*.014),boxShadow:`0 5px 16px ${theme.shadowColor}`}}>{text(n.text,`Заметка ${i+1}`)}</div>)}</div></SceneFrame>; };

/** 30 — Multiple application screens with measured, slow card interpolation. */
export const AppScreenGallery: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const screens=Array.isArray(p.screens)?p.screens.filter((x):x is string=>typeof x==='string').slice(0,5):[]; const rows=screens.length?screens:['','','']; const active=Math.min(rows.length-1,Math.floor(frame/Math.max(1,fps*1.6))); const device=text(p.device,'phone');
 return <SceneFrame props={props}><Heading meta="APP GALLERY" title={text(p.title,'ЭКРАНЫ, КОТОРЫЕ ВЕДУТ ИСТОРИЮ')} /><div style={{position:'relative',flex:1,marginTop:Math.round(height*.025)}}>{rows.map((url,i)=>{const delta=i-active;return <div key={i} style={{position:'absolute',left:'50%',top:'48%',width:device==='phone'?width*.50:width*.76,height:device==='phone'?height*.48:height*.35,transform:`translate(-50%,-50%) translateX(${delta*width*.22}px) translateY(${Math.abs(delta)*height*.035}px) rotate(${delta*7}deg) scale(${i===active?1:.78})`,opacity:i===active?1:.5,zIndex:10-Math.abs(delta),border:`8px solid ${theme.text}`,borderRadius:device==='phone'?34:18,overflow:'hidden',boxShadow:`0 25px 55px ${theme.shadowColor}`}}><Media url={url} style={{width:'100%',height:'100%'}} label={`ЭКРАН ${i+1}`}/></div>;})}</div><div style={{fontFamily:fonts.display,color:accent,fontSize:Math.round(height*.017),fontWeight:900}}>{active+1} / {rows.length}</div></SceneFrame>; };

/** 31 — Reordered browser/chat/table/media windows. */
export const LayeredWindowStack: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const windows=asRows(p.windows).slice(0,4); const rows=windows.length?windows:[{label:'BROWSER',url:''},{label:'CHAT',url:''},{label:'TABLE',url:''}]; const focus=Math.min(rows.length-1,Math.floor(frame/Math.max(1,fps*1.8)));
 return <SceneFrame props={props}><Heading meta="WORKFLOW STACK" title={text(p.title,'ОКНА СОБИРАЮТСЯ В ПРОЦЕСС')} /><div style={{position:'relative',flex:1,marginTop:15}}>{rows.map((r,i)=>{const active=i===focus;const x=(i-focus)*width*.12;const y=(i-focus)*height*.045;return <div key={i} style={{position:'absolute',left:'50%',top:'48%',width:width*.70,height:height*.32,transform:`translate(-50%,-50%) translate(${x}px,${y}px) scale(${active?1:.86})`,zIndex:active?10:i,borderRadius:20,overflow:'hidden',background:theme.surface,border:`1px solid ${active?accent:`${theme.muted}55`}`,boxShadow:`0 18px 45px ${theme.shadowColor}AA`}}><div style={{height:34,background:theme.bg,padding:'0 12px',display:'flex',alignItems:'center',fontFamily:fonts.display,color:active?accent:theme.muted,fontSize:Math.round(height*.015),fontWeight:900}}>{text(r.label,`WINDOW ${i+1}`)}</div><Media url={text(r.url,text(r.mediaUrl))} style={{height:'calc(100% - 34px)'}} label={text(r.label,'WINDOW')}/></div>;})}</div></SceneFrame>; };

/** 32 — Controlled screenshot compare with date/source ribbons. */
export const ImageEvidenceCompare: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {width,height}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const side=(url:string,meta:unknown,label:string,active:boolean)=><SafeFlex style={{borderRadius:20,overflow:'hidden',border:`1px solid ${active?accent:`${theme.muted}55`}`,background:theme.surface}}><Media url={url} style={{height:height*.33}} label={label}/><div style={{padding:Math.round(width*.023),fontFamily:fonts.body,color:active?accent:theme.muted,fontSize:Math.round(height*.016),lineHeight:1.2}}>{typeof meta==='string'?meta:label}</div></SafeFlex>;
 return <SceneFrame props={props}><Heading meta="EVIDENCE COMPARE" title={text(p.title,'СРАВНИВАЕМ ДВА СКРИНШОТА')} /><SafeRow gap={Math.round(width*.024)} style={{marginTop:Math.round(height*.04)}}>{side(text(p.leftImage),p.leftMeta,'ИСТОЧНИК A',false)}{side(text(p.rightImage),p.rightMeta,'ИСТОЧНИК B',true)}</SafeRow><div style={{marginTop:Math.round(height*.025),padding:Math.round(width*.025),borderRadius:16,background:`${accent}13`,fontFamily:fonts.body,color:theme.text,fontWeight:650,fontSize:Math.round(height*.019),lineHeight:1.22}}><b style={{color:accent}}>Различие:</b> {text(p.difference,'Опишите проверяемое различие, не делайте вывод за зрителя.')}</div></SceneFrame>; };
