import React from 'react';
import {Img, OffthreadVideo, useCurrentFrame, useVideoConfig} from 'remotion';
import {BaseSceneProps} from '../VideoSpec.schema';
import {resolveMotion} from '../lib/motion';
import {fitWrapped} from '../theme/layout';
import {useStyle} from '../theme/StyleContext';
import {asNumber, asRows, asText, clamp01, isVideoMedia, resolveMedia, SafeFlex, SafeRow, SceneFrame, sceneHeadingStyle} from './expansion_shared';

type Props = BaseSceneProps & Record<string, unknown>;
const text = (v: unknown, f = '') => asText(v, f);

const CommunityHeader: React.FC<{title: string; meta?: string}> = ({title, meta = 'COMMUNITY'}) => { const {height} = useVideoConfig(); const {theme, fonts, accent} = useStyle(); return <><div style={{fontFamily: fonts.display, color: accent, fontSize: Math.round(height * .017), letterSpacing: 1.8, fontWeight: 900}}>{meta}</div><div style={{...sceneHeadingStyle(height, fonts, theme.text), marginTop: 7}}>{title}</div></>; };
const In: React.FC<{props: BaseSceneProps; delay?: number; children: React.ReactNode; style?: React.CSSProperties}> = ({props, delay = 0, children, style}) => { const frame = useCurrentFrame(); const {fps, height} = useVideoConfig(); const p = clamp01(resolveMotion(props.motion ?? 'reveal', fps, 'reveal')(frame - delay, 0, 1)); return <div style={{opacity:p, transform:`translateY(${Math.round((1-p)*height*.024)}px)`, ...style}}>{children}</div>; };
const Avatar: React.FC<{label: string; image?: string; size?: number}> = ({label, image, size = 54}) => { const {theme, fonts, accent} = useStyle(); const source = resolveMedia(image); return <div style={{width:size, height:size, borderRadius:'50%', overflow:'hidden', flexShrink:0, background:accent, color:theme.bg, display:'flex', alignItems:'center', justifyContent:'center', fontFamily:fonts.display, fontWeight:900}}>{source && !isVideoMedia(source) ? <Img src={source} style={{width:'100%',height:'100%',objectFit:'cover'}}/> : label.slice(0,2).toUpperCase()}</div>; };

/** 13 — Configurable Telegram-style channel post. */
export const TelegramChannelPost: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {width,height}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const channel=text(p.channel,'LLM Hubs'); const handle=text(p.handle,'@llm_hubs'); const post=text(p.postText,text(p.text,'Короткий практический разбор: сначала источник, затем тест на своём workload.')); const media=resolveMedia(p.mediaUrl); const reactions=asRows(p.reactions).slice(0,4); const fit=fitWrapped({text:post,maxWidth:width*.70,maxLines:5,fontFamily:fonts.body,fontWeight:650,maxFontSize:Math.round(height*.025),minFontSize:Math.round(height*.016)});
  return <SceneFrame props={props}><div style={{height:'100%',display:'flex',alignItems:'center',justifyContent:'center'}}><In props={props} style={{width:width*.84}}><div style={{borderRadius:26,overflow:'hidden',background:`${theme.surface}F4`,border:`1px solid ${accent}77`,boxShadow:`0 20px 60px ${theme.shadowColor}AA`}}><div style={{padding:`${Math.round(height*.022)}px ${Math.round(width*.033)}px`,display:'flex',gap:12,alignItems:'center',borderBottom:`1px solid ${theme.muted}33`}}><Avatar label={channel} image={text(p.avatar)} size={Math.round(height*.052)}/><SafeFlex><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.025)}}>{channel}</div><div style={{fontFamily:fonts.body,color:accent,fontSize:Math.round(height*.016),fontWeight:700,marginTop:2}}>{handle}</div></SafeFlex><div style={{fontFamily:fonts.display,color:accent,fontWeight:900}}>•••</div></div><div style={{padding:Math.round(width*.033)}}>{media && <div style={{height:Math.round(height*.25),borderRadius:18,overflow:'hidden',background:theme.bg,marginBottom:Math.round(height*.02)}}>{isVideoMedia(media)?<OffthreadVideo src={media} volume={0} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<Img src={media} style={{width:'100%',height:'100%',objectFit:'cover'}}/>}</div>}<div style={{fontFamily:fonts.body,color:theme.text,fontSize:fit.fontSize,lineHeight:1.25,fontWeight:650}}>{post}</div><SafeRow gap={10} style={{alignItems:'center',marginTop:Math.round(height*.025)}}>{reactions.length?reactions.map((r,i)=><div key={i} style={{borderRadius:999,padding:'6px 9px',background:`${accent}18`,border:`1px solid ${accent}55`,fontFamily:fonts.display,color:accent,fontSize:Math.round(height*.015),fontWeight:850}}>{text(r.emoji,'👍')} {asNumber(r.count,0)}</div>):<div style={{borderRadius:999,padding:'6px 9px',background:`${accent}18`,fontFamily:fonts.display,color:accent,fontSize:Math.round(height*.015),fontWeight:850}}>🔥 124</div>}<SafeFlex/><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.015)}}>{asNumber(p.views,0) ? `${asNumber(p.views).toLocaleString()} views` : text(p.time,'сейчас')}</div></SafeRow>{text(p.cta) && <div style={{fontFamily:fonts.display,color:accent,fontSize:Math.round(height*.018),fontWeight:900,marginTop:Math.round(height*.022)}}>{text(p.cta)} →</div>}</div></div></In></div></SceneFrame>; };

/** 14 — Controlled channel feed scroll. */
export const TelegramFeedScroll: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const channel=text(p.channel,'LLM Hubs'); const posts=asRows(p.posts).slice(0,5); const rows=posts.length?posts:[{text:'Новый разбор модели и цены.',tag:'RELEASE'},{text:'Три первоисточника по важному claim.',tag:'RESEARCH'},{text:'Как проверить тариф перед запуском.',tag:'GUIDE'}]; const focus=text(p.focusPostId,'1'); const motion=clamp01(resolveMotion(props.motion??'reveal',fps,'reveal')(frame,0,1));
  return <SceneFrame props={props}><CommunityHeader title={channel} meta="TELEGRAM FEED"/><div style={{marginTop:Math.round(height*.035),display:'flex',flexDirection:'column',gap:Math.round(height*.018),transform:`translateY(${Math.round((1-motion)*height*.06)}px)`}}>{rows.map((row,i)=>{const active=String(i+1)===focus||text(row.id)===focus;return <In key={i} props={props} delay={i*6}><div style={{borderRadius:20,padding:Math.round(width*.03),background:active?`${accent}18`:`${theme.surface}E8`,border:`1px solid ${active?accent:`${theme.muted}44`}`}}><div style={{fontFamily:fonts.display,color:active?accent:theme.muted,fontWeight:900,fontSize:Math.round(height*.014),letterSpacing:1}}>{text(row.tag,'POST')}</div><div style={{fontFamily:fonts.body,color:theme.text,fontWeight:700,fontSize:Math.round(height*.022),lineHeight:1.22,marginTop:7}}>{text(row.text,'Пост канала')}</div></div></In>})}</div></SceneFrame>; };

/** 15 — Original post and its transparent forwarding path. */
export const TelegramForwardChain: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height,width}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const origin=typeof p.origin==='object'&&p.origin?p.origin as Record<string,unknown>:{}; const forwards=asRows(p.forwards).slice(0,4); const rows=forwards.length?forwards:[{channel:'AI Новости',note:'переслал разбор'},{channel:'Команда',note:'обсуждает вывод'}];
 return <SceneFrame props={props}><CommunityHeader title={text(p.title,'КАК РАСПРОСТРАНЯЕТСЯ ПОСТ')} meta="FORWARD CHAIN"/><div style={{marginTop:Math.round(height*.04)}}><div style={{borderRadius:18,padding:Math.round(width*.03),background:`${accent}16`,border:`1px solid ${accent}66`,fontFamily:fonts.body,color:theme.text,fontWeight:700,fontSize:Math.round(height*.021)}}><b style={{color:accent}}>{text(origin.channel,'Исходный канал')}</b><br/>{text(origin.text,'Первичный пост и источник.')}</div>{rows.map((row,i)=><React.Fragment key={i}><div style={{height:Math.round(height*.03),marginLeft:Math.round(width*.08),borderLeft:`2px dashed ${accent}`}}/><In props={props} delay={i*8}><SafeRow gap={12} style={{alignItems:'center',padding:Math.round(width*.028),borderRadius:18,background:`${theme.surface}E8`,border:`1px solid ${theme.muted}44`}}><div style={{width:28,height:28,borderRadius:'50%',background:accent,color:theme.bg,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900}}>↗</div><SafeFlex><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.02)}}>{text(row.channel,`Канал ${i+1}`)}</div><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.016),marginTop:3}}>{text(row.note)}</div></SafeFlex></SafeRow></In></React.Fragment>)}</div></SceneFrame>; };

/** 16 — Supplied social reactions and reach. */
export const ReactionPulse: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const reactions=asRows(p.reactions).slice(0,5); const rows=reactions.length?reactions:[{emoji:'🔥',count:124},{emoji:'👍',count:88},{emoji:'🧠',count:52}]; const q=clamp01(resolveMotion(props.motion??'reveal',fps,'reveal')(frame,0,1));
 return <SceneFrame props={props}><CommunityHeader title={text(p.title,'ОТКЛИК АУДИТОРИИ')} meta={text(p.period,'REACTION PULSE')}/><div style={{marginTop:Math.round(height*.055),display:'flex',gap:Math.round(width*.025),flexWrap:'wrap'}}>{rows.map((row,i)=><In key={i} props={props} delay={i*6}><div style={{minWidth:Math.round(width*.18),borderRadius:20,padding:`${Math.round(height*.02)}px ${Math.round(width*.025)}px`,background:`${i===0?accent:theme.cyan}19`,border:`1px solid ${i===0?accent:theme.cyan}`,fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.028)}}>{text(row.emoji,'👍')} {Math.round(asNumber(row.count)*q)}</div></In>)}</div><div style={{marginTop:Math.round(height*.05),borderRadius:18,padding:Math.round(width*.03),background:`${theme.surface}DD`,fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.022)}}><b style={{color:theme.text}}>{asNumber(p.views,0).toLocaleString() || '—'}</b> просмотров · {asNumber(p.comments,0)} комментариев</div></SceneFrame>; };

/** 17 — Original claim compared with a quoted repost. */
export const QuoteRepost: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {width,height}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const original=typeof p.original==='object'&&p.original?p.original as Record<string,unknown>:{}; const commentary=text(p.commentary,'Проверьте дату, scope и условия до того, как повторять вывод.');
 return <SceneFrame props={props}><CommunityHeader title={text(p.title,'РЕПОСТ С РАЗБОРОМ')} meta="QUOTE REPOST"/><div style={{marginTop:Math.round(height*.04),display:'flex',flexDirection:'column',gap:Math.round(height*.022)}}><div style={{padding:Math.round(width*.03),borderRadius:18,background:`${theme.surface}DD`,border:`1px solid ${theme.muted}44`}}><div style={{fontFamily:fonts.display,color:theme.muted,fontWeight:900,fontSize:Math.round(height*.015)}}>{text(original.author,'ИСТОЧНИК')}</div><div style={{fontFamily:fonts.body,color:theme.text,fontSize:Math.round(height*.022),lineHeight:1.25,marginTop:8}}>{text(original.text,'Исходный тезис из поста.')}</div></div><div style={{padding:Math.round(width*.035),borderRadius:20,background:`${accent}16`,border:`1.5px solid ${accent}77`}}><div style={{fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.016)}}>{text(p.author,'КОММЕНТАРИЙ')}</div><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:850,fontSize:Math.round(height*.028),lineHeight:1.12,marginTop:8}}>{commentary}</div><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.016),marginTop:12}}>{text(p.source)}</div></div></div></SceneFrame>; };

/** 18 — Question, answer and resource cards. */
export const CommunityFAQ: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height,width}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const questions=Array.isArray(p.questions)?p.questions.filter((x):x is string=>typeof x==='string'):[]; const answers=Array.isArray(p.answers)?p.answers.filter((x):x is string=>typeof x==='string'):[]; const count=Math.min(3,Math.max(questions.length,answers.length,1));
 return <SceneFrame props={props}><CommunityHeader title={text(p.title,'ВОПРОСЫ СООБЩЕСТВА')} meta="FAQ"/><div style={{marginTop:Math.round(height*.035),display:'flex',flexDirection:'column',gap:Math.round(height*.02)}}>{Array.from({length:count},(_,i)=><In key={i} props={props} delay={i*7}><div style={{borderRadius:20,padding:Math.round(width*.03),background:i%2?`${accent}14`:`${theme.surface}E8`,border:`1px solid ${i%2?accent:`${theme.muted}44`}`}}><div style={{fontFamily:fonts.display,color:i%2?accent:theme.text,fontWeight:900,fontSize:Math.round(height*.019)}}>Q. {questions[i]||'Что проверить сначала?'}</div><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.019),lineHeight:1.22,marginTop:7}}>A. {answers[i]||'Откройте первоисточник и зафиксируйте дату.'}</div></div></In>)}</div></SceneFrame>; };

/** 19 — High-legibility release note terminal. */
export const ChangelogTerminal: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height,width}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const changes=asRows(p.changes).slice(0,6); const rows=changes.length?changes:[{kind:'added',text:'Новый режим reasoning'},{kind:'changed',text:'Обновлён тариф'},{kind:'check',text:'Проверьте дату вступления'}];
 return <SceneFrame props={props}><div style={{borderRadius:24,overflow:'hidden',background:'#0A0F19',border:`1px solid ${accent}66`,boxShadow:`0 0 40px ${accent}19`}}><div style={{padding:`${Math.round(height*.015)}px ${Math.round(width*.03)}px`,background:'#111B2B',display:'flex',gap:7}}><span style={{color:'#FF6A6A'}}>●</span><span style={{color:'#FFD36A'}}>●</span><span style={{color:accent}}>●</span><span style={{fontFamily:fonts.body,color:'#95A4BE',fontSize:Math.round(height*.015),marginLeft:8}}>{text(p.product,'product')} · {text(p.version,'vNext')}</span></div><div style={{padding:Math.round(width*.04)}}><div style={{fontFamily:'monospace',color:accent,fontWeight:900,fontSize:Math.round(height*.018)}}>$ changelog --date {text(p.date,'today')}</div><div style={{marginTop:Math.round(height*.025),display:'flex',flexDirection:'column',gap:10}}>{rows.map((row,i)=><div key={i} style={{fontFamily:'monospace',color:'#E9F2FF',fontSize:Math.round(height*.018),lineHeight:1.25}}><span style={{color: text(row.kind).includes('add')?accent:'#FFCF66'}}>[{text(row.kind,'change').toUpperCase()}]</span> {text(row.text)}</div>)}</div></div></div></SceneFrame>; };

/** 20 — Prompt A/B comparison. */
export const PromptABLab: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {width,height}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const promptA=text(p.promptA,'Кратко объясни тему.'); const promptB=text(p.promptB,'Объясни тему, укажи источник и ограничение.'); const resultA=text(p.resultA,'Общий ответ'); const resultB=text(p.resultB,'Проверяемый ответ'); const card=(label:string,prompt:string,result:string,good:boolean)=><SafeFlex style={{padding:Math.round(width*.028),borderRadius:20,background:good?`${accent}14`:`${theme.surface}E8`,border:`1px solid ${good?accent:`${theme.muted}44`}`}}><div style={{fontFamily:fonts.display,color:good?accent:theme.muted,fontWeight:900,fontSize:Math.round(height*.017)}}>{label}</div><div style={{fontFamily:fonts.body,color:theme.text,fontWeight:650,fontSize:Math.round(height*.018),lineHeight:1.2,marginTop:10}}>{prompt}</div><div style={{height:1,background:`${theme.muted}44`,margin:`${Math.round(height*.02)}px 0`}}/><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:850,fontSize:Math.round(height*.02)}}>{result}</div></SafeFlex>;
 return <SceneFrame props={props}><CommunityHeader title={text(p.title,'ЛАБОРАТОРИЯ ПРОМПТОВ')} meta="PROMPT A/B"/><SafeRow gap={Math.round(width*.025)} style={{marginTop:Math.round(height*.04)}}>{card('PROMPT A',promptA,resultA,false)}{card('PROMPT B',promptB,resultB,true)}</SafeRow></SceneFrame>; };

/** 21 — Agent pipeline console, intentionally non-sensitive. */
export const AgentRunConsole: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height,width}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const steps=asRows(p.steps).slice(0,6); const rows=steps.length?steps:[{label:'Research',status:'done'},{label:'Проверка источников',status:'done'},{label:'Storyboard',status:'running'},{label:'Render',status:'queued'}];
 return <SceneFrame props={props}><CommunityHeader title={text(p.title,'ЗАПУСК АГЕНТА')} meta={text(p.status,'PIPELINE TRACE')}/><div style={{marginTop:Math.round(height*.04),borderRadius:22,overflow:'hidden',border:`1px solid ${theme.muted}44`,background:`${theme.surface}E8`}}>{rows.map((row,i)=>{const status=text(row.status,'queued'); const color=status==='done'?accent:status==='running'?theme.cyan:theme.muted;return <In key={i} props={props} delay={i*5}><SafeRow gap={12} style={{padding:`${Math.round(height*.016)}px ${Math.round(width*.03)}px`,alignItems:'center',borderBottom:i<rows.length-1?`1px solid ${theme.muted}2D`:undefined}}><div style={{width:11,height:11,borderRadius:'50%',background:color,boxShadow:status==='running'?`0 0 10px ${color}`:'none'}}/><SafeFlex style={{fontFamily:fonts.display,color:theme.text,fontWeight:800,fontSize:Math.round(height*.019)}}>{text(row.label,`Шаг ${i+1}`)}</SafeFlex><div style={{fontFamily:fonts.display,color,fontWeight:900,fontSize:Math.round(height*.014)}}>{status.toUpperCase()}</div></SafeRow></In>})}</div></SceneFrame>; };

/** 22 — Browser table with one inspected cell. */
export const BrowserDecisionTable: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const {height,width}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const columns=Array.isArray(p.columns)?p.columns.filter((x):x is string=>typeof x==='string').slice(0,4):['Модель','Цена','Качество']; const data=asRows(p.rows).slice(0,4); const rows=data.length?data:[{model:'A',price:'низкая',quality:'88'},{model:'B',price:'средняя',quality:'92'}]; const selected=typeof p.selectedCell==='object'&&p.selectedCell?p.selectedCell as Record<string,unknown>:{row:1,column:2};
 return <SceneFrame props={props}><CommunityHeader title={text(p.title,'ТАБЛИЦА РЕШЕНИЯ')} meta="BROWSER TABLE"/><div style={{marginTop:Math.round(height*.035),borderRadius:20,overflow:'hidden',border:`1px solid ${accent}66`,background:theme.surface}}><div style={{padding:`10px ${Math.round(width*.025)}px`,background:theme.bg,fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.015),whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{text(p.url,'provider.example/compare')}</div><div style={{display:'grid',gridTemplateColumns:`repeat(${columns.length},minmax(0,1fr))`,gap:1,background:`${theme.muted}33`}}>{columns.map(c=><div key={c} style={{padding:10,background:theme.bg,fontFamily:fonts.display,color:theme.muted,fontWeight:900,fontSize:Math.round(height*.014),overflow:'hidden',whiteSpace:'nowrap',textOverflow:'ellipsis'}}>{c}</div>)}{rows.flatMap((row,ri)=>columns.map((column,ci)=>{const active=asNumber(selected.row,1)===ri+1&&asNumber(selected.column,1)===ci+1;return <div key={`${ri}-${column}`} style={{padding:10,minWidth:0,background:active?`${accent}24`:theme.surface,fontFamily:fonts.body,color:active?theme.text:theme.muted,fontWeight:active?850:650,fontSize:Math.round(height*.016),overflow:'hidden',whiteSpace:'nowrap',textOverflow:'ellipsis',outline:active?`1px solid ${accent}`:undefined}}>{text(row[column.toLowerCase()],text(row[column], '—'))}</div>}))}</div></div>{text(p.caption) && <div style={{fontFamily:fonts.body,color:accent,fontSize:Math.round(height*.018),marginTop:12}}>{text(p.caption)}</div>}</SceneFrame>; };
