import React from 'react';
import {interpolate, OffthreadVideo, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {BaseSceneProps} from '../VideoSpec.schema';
import {Backdrop} from '../theme/Backdrop';
import {useStyle} from '../theme/StyleContext';
import {getSafeArea} from '../lib/safeArea';
import {resolveMotion} from '../lib/motion';
import {fitOneLine, fitWrapped} from '../theme/layout';

type Props = BaseSceneProps & Record<string, unknown>;
const clamp = (value: number) => Math.max(0, Math.min(1, value));
const text = (value: unknown, fallback = '') => typeof value === 'string' ? value : fallback;
const rows = (value: unknown) => Array.isArray(value) ? value.filter((item): item is Record<string, unknown> => !!item && typeof item === 'object') : [];

const Canvas: React.FC<{props: BaseSceneProps; children: React.ReactNode}> = ({props, children}) => {
  const {width, height} = useVideoConfig(); const safe = getSafeArea(width, height, props.safeArea ?? 'platform'); const {theme} = useStyle();
  return <div style={{position:'absolute',inset:0,background:theme.bg,overflow:'hidden'}}><Backdrop/><div style={{position:'absolute',top:safe.top,left:safe.left,width:safe.width,height:safe.height,boxSizing:'border-box'}}>{children}</div></div>;
};
const Header: React.FC<{title: string; meta?: string}> = ({title, meta}) => { const {height,width}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); return <><div style={{fontFamily:fonts.display,color:accent,fontSize:Math.round(height*.018),fontWeight:850,letterSpacing:Math.round(width*.0026),textTransform:'uppercase'}}>{meta || 'INTERACTION'}</div><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.042),lineHeight:1.05,marginTop:7}}>{title}</div></>; };
const MediaSurface: React.FC<{url?: string; label?: string; height?: number}> = ({url,label='MEDIA',height=360}) => { const {theme,fonts,accent}=useStyle(); const source=url&&(url.startsWith('http://')||url.startsWith('https://')||url.startsWith('data:'))?url:url?staticFile(url):''; const isVideo=/\.(mp4|webm|mov)(?:[?#].*)?$/i.test(source); return <div style={{height,borderRadius:22,overflow:'hidden',position:'relative',background:isVideo?theme.bg:source?`center / cover no-repeat url(${source})`:`linear-gradient(145deg, ${theme.surface}, ${theme.bg})`,border:`1px solid ${accent}66`,boxShadow:`0 0 30px ${accent}17`}}>{isVideo?<OffthreadVideo src={source} volume={0} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:!source&&<><div style={{position:'absolute',inset:0,opacity:.32,backgroundImage:`linear-gradient(${theme.muted}18 1px, transparent 1px),linear-gradient(90deg, ${theme.muted}18 1px, transparent 1px)`,backgroundSize:'34px 34px'}}/><div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',fontFamily:fonts.display,color:accent,fontWeight:900,letterSpacing:2,fontSize:18}}>{label}</div></>}</div> };

/** Prompt input with typed presentation and explicit send action. */
export const PromptComposer: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const e=clamp(resolveMotion(props.motion??'reveal',fps,'reveal')(frame,0,1)); const prompt=text(p.prompt,text(p.text,'Составь план проверки claim по первоисточнику')); const provider=text(p.provider,'LLM WORKSPACE'); const send=text(p.sendLabel,'Отправить'); const visible=Math.min(prompt.length,Math.max(0,Math.round((frame-Math.round(fps*.18))*prompt.length/Math.max(fps*.6,1))));
  return <Canvas props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',opacity:e}}><Header title={provider} meta="PROMPT COMPOSER"/><div style={{marginTop:Math.round(height*.04),border:`1.5px solid ${accent}88`,borderRadius:26,background:`${theme.surface}E8`,padding:Math.round(width*.04)}}><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.018)}}>Новый запрос</div><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:760,fontSize:Math.round(height*.031),lineHeight:1.25,minHeight:Math.round(height*.12),marginTop:12}}>{prompt.slice(0,visible)}<span style={{display:'inline-block',width:3,height:Math.round(height*.030),marginLeft:4,verticalAlign:'text-bottom',background:accent,opacity:visible<prompt.length?1:0}}/></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:Math.round(height*.025)}}><span style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.016)}}>⌘ Enter</span><span style={{fontFamily:fonts.display,color:theme.bg,background:accent,borderRadius:999,padding:'10px 16px',fontWeight:900,fontSize:Math.round(height*.017)}}>{send} ↑</span></div></div></div></Canvas>; };

/** Compact provider-branded chat with actual avatar token. */
export const ProviderChat: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const m=resolveMotion(props.motion??'reveal',fps,'reveal'); const provider=text(p.provider,text(p.title,'Provider')); const avatar=text(p.avatarText,provider.slice(0,2).toUpperCase()); const avatarUrl=text(p.avatarUrl,''); const avatarSrc=avatarUrl&&(avatarUrl.startsWith('http://')||avatarUrl.startsWith('https://')||avatarUrl.startsWith('data:'))?avatarUrl:avatarUrl?staticFile(avatarUrl):''; const Avatar: React.FC<{size:number;fontSize:number}> = ({size,fontSize}) => <div style={{width:size,height:size,borderRadius:'50%',background:accent,color:theme.bg,display:'flex',alignItems:'center',justifyContent:'center',fontFamily:fonts.display,fontWeight:900,fontSize,overflow:'hidden',flexShrink:0}}>{avatarSrc?<img src={avatarSrc} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:avatar}</div>; const prompt=text(p.prompt,'Как выбрать режим?'); const answer=text(p.answer,text(p.text,'Начните с простого effort и повышайте его только по факту сложности задачи.')); const chips=Array.isArray(p.chips)?p.chips.filter((x):x is string=>typeof x==='string').slice(0,4):['LOW','HIGH','MAX']; const a=clamp(m(frame,0,1));const b=clamp(m(frame-Math.round(fps*.14),0,1));
  return <Canvas props={props}><div style={{height:'100%',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:width*.86,border:`1px solid ${accent}88`,borderRadius:28,overflow:'hidden',background:`${theme.surface}EE`,boxShadow:`0 22px 54px ${theme.shadowColor}AA`,opacity:a,transform:`translateY(${Math.round((1-a)*height*.04)}px)`}}><div style={{display:'flex',alignItems:'center',gap:12,padding:`${Math.round(height*.022)}px ${Math.round(width*.034)}px`,borderBottom:`1px solid ${theme.muted}33`}}><Avatar size={Math.round(height*.052)} fontSize={Math.round(height*.018)}/><div style={{flex:1}}><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.026)}}>{provider}</div><div style={{fontFamily:fonts.body,color:accent,fontWeight:750,fontSize:Math.round(height*.014),marginTop:3}}>AI ASSISTANT</div></div><div style={{color:accent,fontFamily:fonts.display,fontSize:Math.round(height*.014),fontWeight:900}}>●</div></div><div style={{padding:Math.round(width*.034),display:'flex',flexDirection:'column',gap:Math.round(height*.022)}}><div style={{alignSelf:'flex-end',maxWidth:'78%',border:`1px solid ${accent}66`,background:`${accent}1C`,borderRadius:'17px 17px 4px 17px',padding:'12px 14px',fontFamily:fonts.body,color:theme.text,fontSize:Math.round(height*.023),lineHeight:1.25}}>{prompt}</div><div style={{display:'flex',gap:10,opacity:b}}><Avatar size={Math.round(height*.032)} fontSize={Math.round(height*.012)}/><div style={{border:`1px solid ${theme.muted}44`,background:theme.bg,borderRadius:'17px 17px 17px 4px',padding:'13px 14px',fontFamily:fonts.body,color:theme.text,fontWeight:650,fontSize:Math.round(height*.022),lineHeight:1.26}}>{answer}<div style={{display:'flex',gap:7,marginTop:12,flexWrap:'wrap'}}>{chips.map((chip,i)=><span key={chip} style={{padding:'4px 8px',borderRadius:999,border:`1px solid ${i===1?accent:theme.muted}`,color:i===1?accent:theme.muted,fontFamily:fonts.display,fontSize:Math.round(height*.013),fontWeight:900}}>{chip}</span>)}</div></div></div></div></div></div></Canvas>; };

/** Platform-neutral stack of notification cards. */
export const NotificationStack: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const m=resolveMotion(props.motion??'reveal',fps,'reveal'); const notes=rows(p.notifications).slice(0,3); const items=notes.length?notes:[{app:'UPDATE',text:'Новый релиз доступен'},{app:'EVIDENCE',text:'Источник проверен'},{app:'NEXT STEP',text:'Откройте полный разбор'}]; return <Canvas props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center'}}><Header title={text(p.title,'НОВЫЕ СИГНАЛЫ')} /><div style={{marginTop:Math.round(height*.04),display:'flex',flexDirection:'column',gap:Math.round(height*.018)}}>{items.map((note,i)=>{const q=clamp(m(frame-i*Math.round(fps*.14),0,1));return <div key={i} style={{border:`1px solid ${i===0?accent:`${theme.muted}55`}`,borderRadius:21,background:i===0?`${accent}17`:`${theme.surface}E8`,padding:`${Math.round(height*.018)}px ${Math.round(width*.03)}px`,display:'flex',alignItems:'center',gap:12,opacity:q,transform:`translateX(${Math.round((1-q)*width*.09)}px)`}}><div style={{width:Math.round(height*.04),height:Math.round(height*.04),borderRadius:12,background:i===0?accent:theme.muted,display:'flex',alignItems:'center',justifyContent:'center',color:theme.bg,fontWeight:900}}>●</div><div style={{minWidth:0}}><div style={{fontFamily:fonts.display,color:i===0?accent:theme.muted,fontSize:Math.round(height*.014),fontWeight:900,letterSpacing:1}}>{text(note.app,'NOTICE')}</div><div style={{fontFamily:fonts.body,color:theme.text,fontSize:Math.round(height*.023),fontWeight:700,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',marginTop:3}}>{text(note.text,'Новое уведомление')}</div></div></div>})}</div></div></Canvas>; };

/** Discussion thread for social proof, feedback and user questions. */
export const CommentThread: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const m=resolveMotion(props.motion??'reveal',fps,'reveal'); const comments=rows(p.comments).slice(0,3); const items=comments.length?comments:[{author:'Аня',text:'Проверила на своём кейсе — логика сходится.'},{author:'Илья',text:'А где смотреть актуальную цену?'},{author:'LLM HUBS',text:'В первоисточнике и pricing page.'}]; return <Canvas props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center'}}><Header title={text(p.title,'ОБСУЖДЕНИЕ')} meta={text(p.platformLabel,'COMMUNITY THREAD')}/><div style={{marginTop:Math.round(height*.035),display:'flex',flexDirection:'column',gap:Math.round(height*.02)}}>{items.map((comment,i)=>{const q=clamp(m(frame-i*Math.round(fps*.13),0,1));const author=text(comment.author,'User');return <div key={i} style={{display:'flex',gap:11,opacity:q,transform:`translateY(${Math.round((1-q)*height*.026)}px)`}}><div style={{width:Math.round(height*.042),height:Math.round(height*.042),borderRadius:'50%',background:i===2?accent:theme.muted,color:theme.bg,fontFamily:fonts.display,fontSize:Math.round(height*.016),fontWeight:900,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}>{author.slice(0,1).toUpperCase()}</div><div style={{borderRadius:'5px 18px 18px 18px',background:i===2?`${accent}14`:`${theme.surface}E8`,border:`1px solid ${i===2?accent:`${theme.muted}44`}`,padding:'11px 13px',flex:1}}><div style={{fontFamily:fonts.display,color:i===2?accent:theme.text,fontWeight:850,fontSize:Math.round(height*.018)}}>{author}</div><div style={{fontFamily:fonts.body,color:theme.text,fontSize:Math.round(height*.021),lineHeight:1.25,marginTop:4}}>{text(comment.text,'Комментарий')}</div></div></div>})}</div></div></Canvas>; };

/** Poll result card with accessible fill labels. */
export const PollResult: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const m=resolveMotion(props.motion??'reveal',fps,'reveal'); const optionRows=rows(p.options); const options=optionRows.length?optionRows:[{label:'Проверить свой workload',value:68},{label:'Выбрать по list price',value:32}]; const question=text(p.question,text(p.title,'КАК ВЫ СРАВНИВАЕТЕ МОДЕЛИ?')); const max=Math.max(...options.map(x=>typeof x.value==='number'?x.value:0),1); return <Canvas props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center'}}><Header title={question} meta="POLL RESULT"/><div style={{marginTop:Math.round(height*.04),display:'flex',flexDirection:'column',gap:Math.round(height*.02)}}>{options.slice(0,4).map((o,i)=>{const q=clamp(m(frame-i*Math.round(fps*.12),0,1));const label=text(o.label,`Вариант ${i+1}`);const v=typeof o.value==='number'?o.value:0;const pct=Math.round(v/max*100);return <div key={label} style={{opacity:q}}><div style={{display:'flex',justifyContent:'space-between',fontFamily:fonts.display,fontSize:Math.round(height*.022),fontWeight:800,color:i===0?theme.text:theme.muted}}><span>{label}</span><span style={{color:i===0?accent:theme.muted}}>{v}%</span></div><div style={{height:Math.round(height*.024),background:`${theme.muted}2B`,borderRadius:99,overflow:'hidden',marginTop:8}}><div style={{height:'100%',width:`${pct*q}%`,borderRadius:99,background:i===0?accent:theme.cyan,boxShadow:i===0?`0 0 14px ${accent}`:'none'}}/></div></div>})}</div></div></Canvas>; };

/** Browser chrome + screenshot slot + numbered tour callouts. */
export const BrowserTour: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const q=clamp(resolveMotion(props.motion??'reveal',fps,'reveal')(frame,0,1)); const steps=rows(p.steps).slice(0,3); const items=steps.length?steps:[{label:'Откройте pricing'},{label:'Проверьте дату'},{label:'Сохраните evidence'}]; const title=text(p.title,'КАК ПРОВЕРИТЬ УСЛОВИЯ'); const url=text(p.url,'provider.com/pricing'); const image=text(p.screenshotUrl,''); return <Canvas props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',opacity:q}}><Header title={title} meta="BROWSER TOUR"/><div style={{marginTop:Math.round(height*.03),border:`1px solid ${accent}77`,borderRadius:22,overflow:'hidden',background:theme.surface}}><div style={{display:'flex',alignItems:'center',gap:7,padding:'10px 14px',borderBottom:`1px solid ${theme.muted}33`}}><span style={{color:'#FF6A6A'}}>●</span><span style={{color:'#FFD36A'}}>●</span><span style={{color:accent}}>●</span><div style={{marginLeft:8,flex:1,borderRadius:999,background:theme.bg,color:theme.muted,padding:'6px 10px',fontFamily:fonts.body,fontSize:Math.round(height*.014),whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{url}</div></div><MediaSurface url={image} label="SCREENSHOT SLOT" height={Math.round(height*.24)}/><div style={{padding:Math.round(width*.028),display:'flex',flexDirection:'column',gap:9}}>{items.map((s,i)=><div key={i} style={{display:'flex',gap:9,alignItems:'center',fontFamily:fonts.body,color:theme.text,fontSize:Math.round(height*.019)}}><span style={{width:22,height:22,borderRadius:'50%',background:accent,color:theme.bg,display:'inline-flex',alignItems:'center',justifyContent:'center',fontFamily:fonts.display,fontWeight:900,fontSize:13}}>{i+1}</span>{text(s.label,`Шаг ${i+1}`)}</div>)}</div></div></div></Canvas>; };

/** Screenshot focus crop with explicit caption, usable with ScreenGuide. */
export const ScreenMagnifier: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const q=clamp(resolveMotion(props.motion??'reveal',fps,'reveal')(frame,0,1)); const caption=text(p.caption,text(p.title,'СМОТРИТЕ НА ЭТОТ БЛОК')); const media=text(p.mediaUrl,''); const focus=typeof p.focus==='string'?p.focus:'FOCUS'; const zoom=typeof p.zoom==='number'?Math.max(1,Math.min(2.5,p.zoom)):1.3; return <Canvas props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',opacity:q}}><Header title={caption} meta="SCREEN MAGNIFIER"/><div style={{position:'relative',marginTop:Math.round(height*.035)}}><div style={{transform:`scale(${zoom})`,transformOrigin:'50% 50%'}}><MediaSurface url={media} label="SCREEN RECORDING / SCREENSHOT" height={Math.round(height*.31)}/></div><div style={{position:'absolute',inset:'22% 20%',border:`3px solid ${accent}`,borderRadius:16,boxShadow:`0 0 0 100vmax ${theme.bg}99, 0 0 20px ${accent}`,pointerEvents:'none'}}/><div style={{position:'absolute',left:'24%',top:'25%',fontFamily:fonts.display,color:accent,fontWeight:900,fontSize:Math.round(height*.016),letterSpacing:1}}>{focus}</div></div></div></Canvas>; };

/** Device-frame media showcase for phone/tablet/desktop clips. */
export const DeviceShowcase: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const q=clamp(resolveMotion(props.motion??'reveal',fps,'reveal')(frame,0,1)); const device=text(p.device,'phone'); const media=text(p.mediaUrl,''); const title=text(p.title,'ПОКАЖИТЕ, А НЕ РАССКАЗЫВАЙТЕ'); const caption=text(p.caption,text(p.text)); const phone=device==='phone'; const frameW=phone?width*.55:width*.82; const frameH=phone?height*.45:height*.32; return <Canvas props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',opacity:q}}><div style={{fontFamily:fonts.display,color:theme.text,fontSize:Math.round(height*.038),fontWeight:900,textAlign:'center',maxWidth:width*.84}}>{title}</div><div style={{width:frameW,height:frameH,borderRadius:phone?32:20,border:`9px solid ${theme.text}`,background:theme.bg,boxShadow:`0 22px 55px ${theme.shadowColor}AA,0 0 30px ${accent}22`,padding:phone?7:5,boxSizing:'border-box',marginTop:Math.round(height*.035),position:'relative'}}><MediaSurface url={media} label={`${device.toUpperCase()} MEDIA`} height={frameH-(phone?14:10)}/>{phone&&<div style={{position:'absolute',top:14,left:'50%',width:Math.round(frameW*.26),height:5,borderRadius:99,background:theme.text,transform:'translateX(-50%)'}}/>}</div>{caption&&<div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.022),lineHeight:1.25,textAlign:'center',marginTop:Math.round(height*.025),maxWidth:width*.74}}>{caption}</div>}</div></Canvas>; };

/** Voice-message player with deterministic bar waveform. */
export const VoiceWave: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const q=clamp(resolveMotion(props.motion??'reveal',fps,'reveal')(frame,0,1)); const speaker=text(p.speaker,'LLM HUBS'); const duration=text(p.duration,'0:18'); const caption=text(p.caption,text(p.text,'Короткий голосовой разбор')); const seed=typeof p.waveformSeed==='number'?p.waveformSeed:4; const bars=Array.from({length:28},(_,i)=>8+((i*17+seed*9)%30)); return <Canvas props={props}><div style={{height:'100%',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:width*.84,borderRadius:28,border:`1px solid ${accent}77`,background:`${theme.surface}E8`,padding:Math.round(width*.045),opacity:q}}><div style={{display:'flex',alignItems:'center',gap:12}}><div style={{width:Math.round(height*.06),height:Math.round(height*.06),borderRadius:'50%',background:accent,color:theme.bg,fontFamily:fonts.display,fontWeight:900,display:'flex',alignItems:'center',justifyContent:'center'}}>▶</div><div style={{minWidth:0,flex:1}}><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.024)}}>{speaker}</div><div style={{display:'flex',alignItems:'center',gap:3,height:36,marginTop:6}}>{bars.map((bar,i)=><span key={i} style={{width:4,height:Math.round(bar*(.55+.45*Math.sin((frame+i*3)/fps*3))),minHeight:4,borderRadius:99,background:i<18?accent:theme.muted,opacity:i<18?1:.55}}/>)}</div><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.017)}}>{duration} · voice message</div></div></div><div style={{fontFamily:fonts.body,color:theme.text,fontSize:Math.round(height*.022),lineHeight:1.25,marginTop:Math.round(height*.026)}}>{caption}</div></div></div></Canvas>; };

/** Video/reel frame for URLs or locally supplied media assets. */
export const VideoFrame: React.FC<BaseSceneProps> = (props) => { const p=props as Props; const frame=useCurrentFrame(); const {width,height,fps}=useVideoConfig(); const {theme,fonts,accent}=useStyle(); const q=clamp(resolveMotion(props.motion??'reveal',fps,'reveal')(frame,0,1)); const media=text(p.mediaUrl,''); const title=text(p.title,'ВСТАВКА ВИДЕО'); const channel=text(p.channel,'CHANNEL'); const duration=text(p.duration,'0:32'); const chapter=text(p.chapter,'ГЛАВНЫЙ МОМЕНТ'); return <Canvas props={props}><div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',opacity:q}}><MediaSurface url={media} label="VIDEO / REEL ASSET" height={Math.round(height*.36)}/><div style={{marginTop:Math.round(height*.022),display:'flex',alignItems:'flex-start',gap:12}}><div style={{width:Math.round(height*.048),height:Math.round(height*.048),borderRadius:12,background:accent,color:theme.bg,fontFamily:fonts.display,fontWeight:900,display:'flex',alignItems:'center',justifyContent:'center'}}>▶</div><div style={{minWidth:0,flex:1}}><div style={{fontFamily:fonts.display,color:theme.text,fontWeight:900,fontSize:Math.round(height*.032),lineHeight:1.05}}>{title}</div><div style={{fontFamily:fonts.body,color:theme.muted,fontSize:Math.round(height*.018),marginTop:5}}>{channel} · {duration}</div></div></div><div style={{display:'inline-flex',alignSelf:'flex-start',fontFamily:fonts.display,color:accent,border:`1px solid ${accent}77`,borderRadius:999,padding:'6px 10px',fontSize:Math.round(height*.014),fontWeight:900,letterSpacing:1,marginTop:Math.round(height*.02)}}>{chapter}</div></div></Canvas>; };
